### ISSUE TITLE
NullReferenceException when trying to convert Single line of text to Multi Line of Text

### ISSUE THREAD

**Issue by JSpin2088** [daryllabar/DLaB.Xrm.XrmToolBoxTools#109]
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at DLaB.AttributeManager.AttributeManagerPlugin.GetStringFormat()
   at DLaB.AttributeManager.AttributeManagerPlugin.GetNewAttributeType()
   at DLaB.AttributeManager.AttributeManagerPlugin.ExecuteSteps()
   at XrmToolBox.Extensibility.PluginControlBase.ExecuteMethod(Action action)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![image](https://user-images.githubusercontent.com/5892471/27735490-84aea2d8-5d65-11e7-8792-d538e9244efd.png)

**Comment by JSpin2088** [comment]
Looks like if you select "Single Line of Text" first, then set it to Text Area, then switch back to Multiple Lines of text, it all works fine. I'm wondering if the GetStringFormat() should even be called for Multi Line of text?

**Comment by daryllabar** [comment]
I ran into this big recently as well.  Unfortunately I won't be able to fix it for a couple weeks...
