### ISSUE TITLE
Cannot implicitly convert type 'void' to 'object'

### ISSUE THREAD

**Issue by daryllabar** [daryllabar/DLaB.Xrm.XrmToolBoxTools#125]
Receiving error attempting to convert a Single Line Field to a multiple line field:

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'void' to 'object'
   at CallSite.Target(Closure , CallSite , Logic , Object , Object , Object , Dictionary`2 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute5[T0,T1,T2,T3,T4,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4)
   at DLaB.AttributeManager.Logic.CopyValue(Object oldAttribute, Object newAttribute, Object value, Dictionary`2 migrationMapping)
   at DLaB.AttributeManager.Logic.CopyData(IOrganizationService service, AttributeMetadata from, AttributeMetadata to, Action actions, Dictionary`2 migrationMapping)
   at DLaB.AttributeManager.Logic.MigrateAttribute(AttributeMetadata fromAtt, AttributeMetadata toAtt, Action actions, Dictionary`2 migrationMapping)
   at DLaB.AttributeManager.Logic.MigrateToTemp(Steps stepsToPerform, AttributeMetadata oldAtt, AttributeMetadata tmpAtt, Action actions, Dictionary`2 migrationMapping)
   at DLaB.AttributeManager.Logic.Run(AttributeMetadata att, String newAttributeSchemaName, Steps stepsToPerform, Action actions, AttributeMetadata newAttributeType, Dictionary`2 migrationMapping)
   at DLaB.AttributeManager.AttributeManagerPlugin.<ExecuteSteps>b__38_2(BackgroundWorker w, DoWorkEventArgs e)

**Comment by ryanperrymba** [comment]
Hey Daryl,  Looking at ways to contribute, I skimmed your open Issues.  

Does this ONLY occur when one of the records' attributes has a null value?

You retrieve the value before calling the function, with 
1092 var value = entity.GetAttributeValue<object>(from.LogicalName);
Per documentation, if the attribute does not exist on the entity, it should return null. 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.entity.getattributevalue?view=dynamics-general-ce-9

Within CopyValue, you check for a null value, and if found, call CopyValueInternal to throw an NotImplementedException.  I noted that your types for the two attributes do not match between CopyValue and CopyValueInternal.  Is this where the system is throwing the implicit type conversion error?

```
        public object CopyValue(dynamic oldAttribute, dynamic newAttribute, object value, Dictionary<string,string> migrationMapping)
        {
            return value == null ? null : CopyValueInternal(oldAttribute, newAttribute, value, migrationMapping);
        }

        private object CopyValueInternal(object oldAttribute, object newAttribute, object value, Dictionary<string, string> migrationMapping)
        {
            throw new NotImplementedException("Not Implemented Value Copy From type: " + oldAttribute.GetType().FullName + " to type: " + newAttribute.GetType().FullName);
        }
```

It appears implicit conversion from object to dynamic is easy. https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/using-type-dynamic#conversions. The opposite, from Dynamic, to object, isn't as clear.  Does it work if all records have a value, or if you change the parameter types?

Just my stab at it, without actually loading up and testing.  Just noticed this is 2 1/2 yrs old. Sorry I'm late to the party.

**Comment by daryllabar** [comment]
Wow man, this is digging into the depths.  No one has reported this problem again, so I'm not sure if this is the one I'd tackle.  I know I've never actually implemented creating all types of attributes with the attribute manager, that is definitely something you could take a stand at.

**Comment by daryllabar** [comment]
Also, this is probably some low hanging fruit as well: https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/issues/241
