### ISSUE TITLE
Unable to skip entities

### ISSUE THREAD

**Issue by tomaleksp** [daryllabar/DLaB.Xrm.XrmToolBoxTools#135]
Hi,

When trying to add entities to skip and then press 'Save' button I get this error:
System.NullReferenceException: Object reference not set to an instance of an object.
   at DLaB.EarlyBoundGenerator.SpecifyEntitiesDialog.<>c.<BtnSave_Click>b__10_0(ListViewItem i)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at DLaB.Common.Config.ToString[T](IEnumerable`1 list, ConfigKeyValueSplitInfo info, Func`2 getString)
   at DLaB.EarlyBoundGenerator.SpecifyEntitiesDialog.BtnSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by daryllabar** [comment]
I blame @MscrmTools.  It should be fixed now with the 2017.11.14 versopm
