### ISSUE TITLE
Can no longer connect to my Dynamics Online instance - log provided

### ISSUE THREAD

**Issue by Lucho1970** [daryllabar/DLaB.Xrm.XrmToolBoxTools#146]
This worked a couple of weeks ago. I know we also had to make changes in our application at the same time in order for it to connect, but I have no way of making changes to this code. 
This should be a common problem, wondering if there is a fix coming?

```
CRM Authentication Type Detected: OnlineFederation
Executing "C:\Users\nomregnjs\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://olokej.api.crm3.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"XrmEntities" /out:"C:\Users\nomregnjs\AppData\Roaming\MscrmTools\XrmToolBox\Settings\Entities\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"olokijmnj@poloplkmnij.onmicrosoft.com" /password:"****************" 
CrmSvcUtil : CRM Service Utility [Version 8.2.1.8676]
c 2015 Microsoft Corporation. All rights reserved

Unable to Login to Dynamics CRM
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Exception: Connection to CRM is not established. Aborting process.
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: CrmSvcUtil
Method	: LoadMetadata
Date	: 9:20:29 AM
Time	: 3/8/2018
Error	: Connection to CRM is not established. Aborting process.
Stack Trace	: at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
======================================================================================================================

Unable to login.  Attempting to login using interactive mode.
Executing "C:\Users\nomregnjs\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"https://olokej.api.crm3.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"XrmEntities" /out:"C:\Users\nomregnjs\AppData\Roaming\MscrmTools\XrmToolBox\Settings\Entities\CrmServiceContext.cs" /servicecontextname:"CrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"olokijmnj@poloplkmnij.onmicrosoft.com" /password:"****************" /interactivelogin:true 
CrmSvcUtil : CRM Service Utility [Version 8.2.1.8676]
c 2015 Microsoft Corporation. All rights reserved

Microsoft.Xrm.Tooling.CrmConnectControl Error: 2 : Error Message: LoadConfigFromFile() - Except - fail
Source	: System.Configuration
Method	: ThrowIfErrors
Date	: 3/8/2018
Time	: 9:20:29 AM
Error	: An error occurred loading a configuration file: Access to the path 'C:\Users\nomregnjs\AppData\Roaming\Microsoft\crmsvcutil\default_crmsvcutil.exe.config' is denied. (C:\Users\nomregnjs\AppData\Roaming\Microsoft\crmsvcutil\default_crmsvcutil.exe.config)
Stack Trace	: at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
   at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.LoadConfigFromFile(Boolean readLocalFirst)
======================================================================================================================
Inner Exception Level 1	: 
Source	: mscorlib
Method	: WinIOError
Date	: 3/8/2018
Time	: 9:20:29 AM
Error	: Access to the path 'C:\Users\nomregnjs\AppData\Roaming\Microsoft\crmsvcutil\default_crmsvcutil.exe.config' is denied.
Stack Trace	: at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForRead(String streamName)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.OpenStreamForRead(String streamName, Boolean assertPermissions)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
======================================================================================================================

Microsoft.Xrm.Tooling.CrmConnectControl Error: 2 : Error Message: LoadConfigFromFile() - Except - fail
Source	: System.Configuration
Method	: ThrowIfErrors
Date	: 3/8/2018
Time	: 9:20:29 AM
Error	: An error occurred loading a configuration file: Access to the path 'C:\Users\nomregnjs\AppData\Roaming\Microsoft\crmsvcutil\default_crmsvcutil.exe.config' is denied. (C:\Users\nomregnjs\AppData\Roaming\Microsoft\crmsvcutil\default_crmsvcutil.exe.config)
Stack Trace	: at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.ClientConfigurationHost.OpenExeConfiguration(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath)
   at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(ConfigurationFileMap fileMap, Boolean isMachine, ConfigurationUserLevel userLevel, String exePath, Boolean preLoad)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.LoadConfigFromFile(Boolean readLocalFirst)
======================================================================================================================
Inner Exception Level 1	: 
Source	: mscorlib
Method	: WinIOError
Date	: 3/8/2018
Time	: 9:20:29 AM
Error	: Access to the path 'C:\Users\nomregnjs\AppData\Roaming\Microsoft\crmsvcutil\default_crmsvcutil.exe.config' is denied.
Stack Trace	: at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForRead(String streamName)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.OpenStreamForRead(String streamName, Boolean assertPermissions)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
======================================================================================================================

CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.SetConfigKeyInformation(Dictionary`2 configKeys)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmServerLoginControl.StartConnectCheck()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.CreateOrganizationServiceEndpoint()
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: Microsoft.Xrm.Tooling.CrmConnectControl
Method	: SetConfigKeyInformation
Date	: 9:20:59 AM
Time	: 3/8/2018
Error	: Object reference not set to an instance of an object.
Stack Trace	: at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.SetConfigKeyInformation(Dictionary`2 configKeys)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmServerLoginControl.StartConnectCheck()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.CreateOrganizationServiceEndpoint()
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
======================================================================================================================

Output file was not updated or not found!  C:\Users\nomregnjs\AppData\Roaming\MscrmTools\XrmToolBox\Settings\Entities\CrmServiceContext.cs

```

**Comment by daryllabar** [comment]
The latest version of the Early Bound Generator uses the V9 CrmSvcUtil.  Have you tried updating to the latest version?

**Comment by Lucho1970** [comment]
I've update the SDK, but it still gives me V8. Where can I find V9?

**Comment by daryllabar** [comment]
Are you not using the CrmSvcUtil that comes with the Early Bound Generator?

**Comment by Lucho1970** [comment]
Well, I am. But that is version 8. So I was looking for V9 and I found it in the SDK, but it is still V8.I did find the instructions to install all the tools using Powershell and I downloaded V9 now. But I have a new error. It seems to get past the log in.
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.NotSupportedException: Could not load provider of type 'DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions'   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)   at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)CrmSvcUtil Error: 2 : ===== DETAIL ======CrmSvcUtil Error: 2 : Source : CrmSvcUtilMethod : CreateInstanceDate : 3:01:58 PMTime : 3/8/2018Error : Could not load provider of type 'DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions'Stack Trace : at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)   at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)======================================================================================================================

**Comment by Lucho1970** [comment]
I think that I have figured it out. I just didn't realize this, but when I looked at the list of addins, Early Bound Generator didn't look like it was installed. Even though it was in my list of Addins. Once I installed it again, it worked!!

**Comment by daryllabar** [comment]
You probably didn't have it updated.  Glad it is working for you...
