### ISSUE TITLE
Attribute Manager - convert attribute type leaves entity form unreadable

### ISSUE THREAD

**Issue by posegate** [daryllabar/DLaB.Xrm.XrmToolBoxTools#167]
Attempting to convert a Global Option set field to a Two Option set field.  Once it is complete, I can no longer open the form for this entity, and I must restore a backup. Is there a step missing in this process?

```
Error message when opening record:
Unexpected Error
An error has occurred. 

Try this action again. If the problem continues, check the Microsoft Dynamics 365 Community for solutions or contact your organization's Microsoft Dynamics 365 Administrator. Finally, you can contact Microsoft Support. If you contact support, please provide the technical details.
Activity ID: 47050d3e-0ccb-48d8-a326-1f5616019c9c
Timestamp: Fri Nov 02 2018 09:31:16 GMT-0500 (Central Daylight Time)
```

Log below:
```
Searching for Existing Attribute ***_event.new_WebpageNeeded
Existing Attribute new_event.new_WebpageNeeded found
Searching for Temp Attribute new_event.new_WebpageNeeded_t_
Temp Attribute new_event.new_WebpageNeeded_t_ found
Searching for New Attribute new_event.new_WebpageNeeded
New Attribute new_event.new_WebpageNeeded found
Only an attribute type change has been requested.  Attempting to differentiate between existing and new.
A Temporary Attribute was found and a request has been made to either remove the existing attribute, create a new attribute, or migrate to temp.  Treating New as not yet created.
Validating Current CRM State Before Performing Steps:
System.InvalidOperationException: Unable to Create Temp!  Temp new_event.new_webpageneeded_t_ already exists!
   at DLaB.AttributeManager.Logic.AssertValidStepsForState(String existingSchemaName, String newSchemaName, Steps stepsToPerform, AttributeMigrationState state, Action actions)
   at DLaB.AttributeManager.Logic.Run(ExecuteStepsInfo info)
   at DLaB.AttributeManager.AttributeManagerPlugin.<>c.<ExecuteSteps>b__34_2(BackgroundWorker w, DoWorkEventArgs e)
Searching for Existing Attribute new_event.new_WebpageNeeded_t_
Existing Attribute new_event.new_WebpageNeeded_t_ found
Searching for Temp Attribute new_event.new_WebpageNeeded_t__t_
Temp Attribute new_event.new_WebpageNeeded_t__t_ not found
Searching for New Attribute new_event.new_WebpageNeeded_t_
New Attribute new_event.new_WebpageNeeded_t_ found
Validating Current CRM State Before Performing Steps:
Beginning Step: Clearing Field Dependencies
Retrieving System Charts with Query: SELECT savedqueryvisualization.savedqueryvisualizationid, savedqueryvisualization.datadescription
FROM savedqueryvisualization
WHERE
( ( ( datadescription Like '%<entity name="new_event">%name="new_webpageneeded_t_"%</entity>%' ) 
 Or ( datadescription Like '%<entity name="new_event">%attribute="new_webpageneeded_t_"%</entity>%' ) 
) 
) 

Retrieving System Charts with Query: SELECT userqueryvisualization.userqueryvisualizationid, userqueryvisualization.datadescription
FROM userqueryvisualization
WHERE
( ( ( datadescription Like '%<entity name="new_event">%name="new_webpageneeded_t_"%</entity>%' ) 
 Or ( datadescription Like '%<entity name="new_event">%attribute="new_webpageneeded_t_"%</entity>%' ) 
) 
) 

Retrieving Views with Query: SELECT savedquery.savedqueryid, savedquery.name, savedquery.querytype, savedquery.fetchxml, savedquery.layoutxml
FROM savedquery
WHERE
( ( ( fetchxml Like '%<entity name="new_event">%name="new_webpageneeded_t_"%</entity>%' ) 
 Or ( fetchxml Like '%<entity name="new_event">%attribute="new_webpageneeded_t_"%</entity>%' ) 
) 
) 

Retrieving Forms with Query: SELECT systemform.formid, systemform.name, systemform.formxml
FROM systemform
WHERE
( systemform.objecttypecode = 'new_event' And formxml Like '%<control %datafieldname="new_webpageneeded_t_"%' ) 

Updating Form Information
Looking up Relationships
No Relationships Found.
Looking up Mappings
No Mappings Found
Checking for Workflow Dependencies
No Workflow Dependencies Found
Publishing Entity new_event
Checking for Delete Dependencies for new_event.new_webpageneeded_t_
Completed Step: Clearing Field Dependencies

Beginning Step: Remove Existing Attribute
Deleting Field new_event.new_webpageneeded_t_
Completed Step: Remove Existing Attribute

Steps Completed!
Searching for Existing Attribute new_event.new_WebpageNeeded
Existing Attribute new_event.new_WebpageNeeded found
Searching for Temp Attribute new_event.new_WebpageNeeded_t_
Temp Attribute new_event.new_WebpageNeeded_t_ not found
Searching for New Attribute new_event.new_WebpageNeeded
New Attribute new_event.new_WebpageNeeded found
Only an attribute type change has been requested.  Attempting to differentiate between existing and new.
No Temporary Attribute was found.  Treating New as not yet created.
Validating Current CRM State Before Performing Steps:
Beginning Step: Create Temp
Creating Attribute new_event.new_WebpageNeeded_t_
Publishing Entity new_event
Completed Step: Create Temp

Beginning Step: Migrate Data To Temp
Retrieving new_event id attribute name
Determining record count (accurate only up to 50000)
Copying data from new_webpageneeded to new_webpageneeded_t_
Copying 1 / 2503
Unable to convert value "946680001" of type "OptionSetValue" to Boolean
Unable to convert value "946680001" of type "OptionSetValue" to Boolean
Unable to convert value "946680001" of type "OptionSetValue" to Boolean
Unable to convert value "946680001" of type "OptionSetValue" to Boolean
Unable to convert value "946680001" of type "OptionSetValue" to Boolean
Unable to convert value "946680001" of type "OptionSetValue" to Boolean
Unable to convert value "946680000" of type "OptionSetValue" to Boolean
Unable to convert value "946680001" of type "OptionSetValue" to Boolean
Data Migration Complete. Total 2503 records processed in 0 seconds.
Completed Step: Migrate Data To Temp

Beginning Step: Migrate To Temp
Checking for Calculated Field Dependencies
No Calculated Dependencies Found
Retrieving System Charts with Query: SELECT savedqueryvisualization.savedqueryvisualizationid, savedqueryvisualization.datadescription
FROM savedqueryvisualization
WHERE
( ( ( datadescription Like '%<entity name="new_event">%name="new_webpageneeded"%</entity>%' ) 
 Or ( datadescription Like '%<entity name="new_event">%attribute="new_webpageneeded"%</entity>%' ) 
) 
) 

Retrieving System Charts with Query: SELECT userqueryvisualization.userqueryvisualizationid, userqueryvisualization.datadescription
FROM userqueryvisualization
WHERE
( ( ( datadescription Like '%<entity name="new_event">%name="new_webpageneeded"%</entity>%' ) 
 Or ( datadescription Like '%<entity name="new_event">%attribute="new_webpageneeded"%</entity>%' ) 
) 
) 

Retrieving Views with Query: SELECT savedquery.savedqueryid, savedquery.name, savedquery.querytype, savedquery.fetchxml, savedquery.layoutxml
FROM savedquery
WHERE
( ( ( fetchxml Like '%<entity name="new_event">%name="new_webpageneeded"%</entity>%' ) 
 Or ( fetchxml Like '%<entity name="new_event">%attribute="new_webpageneeded"%</entity>%' ) 
) 
) 

Retrieving Forms with Query: SELECT systemform.formid, systemform.name, systemform.formxml
FROM systemform
WHERE
( systemform.objecttypecode = 'new_event' And formxml Like '%<control %datafieldname="new_webpageneeded"%' ) 

Checking for Workflow Dependencies
Updating BusinessRule - Hide Show Event URL (9d42fb75-a748-e811-a952-000d3a3101b9)
Updating Trigger f0104d0f-c348-e811-a952-000d3a3101b9 for Workflow
System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: The dependent component Attribute (Id=new_webpageneeded_t_) does not exist.  Failure trying to associate it with ProcessTrigger (Id=f0104d0f-c348-e811-a952-000d3a3101b9) as a dependency. Missing dependency lookup type = AttributeNameLookup. (Fault Detail is equal to Exception details: 
ErrorCode: 0x8004F036
Message: The dependent component Attribute (Id=new_webpageneeded_t_) does not exist.  Failure trying to associate it with ProcessTrigger (Id=f0104d0f-c348-e811-a952-000d3a3101b9) as a dependency. Missing dependency lookup type = AttributeNameLookup.
TimeStamp: 2018-11-02T14:25:11.9062494Z
--
).
```

**Comment by daryllabar** [comment]
Sorry for being slow to respond.  Looks like you restarted half way through the process, but it didn't successfully complete.   The dependent component Attribute (Id=ncjtc_webpageneeded_t_) does not exist.  Failure trying to associate it with ProcessTrigger (Id=f0104d0f-c348-e811-a952-000d3a3101b9) as a dependency. Missing dependency lookup type = AttributeNameLookup.

I'd make a backup of the workflow, and attempt to manually fix it, and let the process continue all the way through to completion.

**Comment by posegate** [comment]
I'm certain I didn't manually restart the process. I've recreated the issue a few times. Could this be due to a business rule on the form related to this attribute?

**Comment by daryllabar** [comment]
Where you able to resolve the workflow error?  

What are your steps to recreate?

If you can send me the before and after versions of the form xml, I'd take a look at them.

**Comment by posegate** [comment]
Okay - here's what I did.
1. Deleted any business rules on forms related to this attribute.
2. Ran the conversion in the tool.
3. Published all customizations
4. Open record and receive this error again
`Activity ID: 74d5bf0b-0ec2-4964-b7ca-6d5e195fd68c
Timestamp: Thu Dec 06 2018 15:40:12 GMT-0600 (Central Standard Time)`
5. CTRL+F5
4. Open record and receive error again

Am I missing something?

Here is the error log
```
Unhandled Exception: System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]: System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> Microsoft.Crm.CrmException: There was a problem while trying to set value for "DefaultTabId" parameter of the control with ID = notescontrol
One of the following may have caused this exception:
1). The property does not exist on the control or it is not public.
2). The property is not writable.
3). The property is not marked with the CrmControlParameter attribute.
   at Microsoft.Crm.Application.ControlActivator.SetPropertyValue(ICrmControl control, ParameterDescriptor parameter, String controlId)
   at Microsoft.Crm.Application.ControlActivator.CreateControl(ControlDescriptor controlDescriptor, FormFactor formFactor, String controlIdPrefix, CustomizableFormExtended hostForm, FormDescriptor hostFormDescriptor, IOrganizationContext context, DynamicMetadataCache metadataCache)
   at Microsoft.Crm.Application.InlineEdit.Mediators.FormMediator.ProcessControlHierarchy(Action`2 controlHandler)
   at Microsoft.Crm.Application.InlineEdit.Mediators.FormMediator.GetInstance(FormFactor formFactor, FormDescriptor descriptor, Guid processId, Int64 processVersionNumber, IOrganizationContext organizationContext)
   at Microsoft.Crm.Application.InlineEdit.ReadFormDataBuilder..ctor(String recordId, String entityTypeCode, Guid formId, FormFactor formFactor)
   at Microsoft.Crm.Application.Pages.Form.FormDataPage.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #E319CBBFDetail: 
<OrganizationServiceFault xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://schemas.microsoft.com/xrm/2011/Contracts">
  <ActivityId>4a5ee631-cd38-4751-94ee-10a3f12d6b3f</ActivityId>
  <ErrorCode>-2147220970</ErrorCode>
  <ErrorDetails xmlns:d2p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
  <Message>System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---&gt; Microsoft.Crm.CrmException: There was a problem while trying to set value for "DefaultTabId" parameter of the control with ID = notescontrol
One of the following may have caused this exception:
1). The property does not exist on the control or it is not public.
2). The property is not writable.
3). The property is not marked with the CrmControlParameter attribute.
   at Microsoft.Crm.Application.ControlActivator.SetPropertyValue(ICrmControl control, ParameterDescriptor parameter, String controlId)
   at Microsoft.Crm.Application.ControlActivator.CreateControl(ControlDescriptor controlDescriptor, FormFactor formFactor, String controlIdPrefix, CustomizableFormExtended hostForm, FormDescriptor hostFormDescriptor, IOrganizationContext context, DynamicMetadataCache metadataCache)
   at Microsoft.Crm.Application.InlineEdit.Mediators.FormMediator.ProcessControlHierarchy(Action`2 controlHandler)
   at Microsoft.Crm.Application.InlineEdit.Mediators.FormMediator.GetInstance(FormFactor formFactor, FormDescriptor descriptor, Guid processId, Int64 processVersionNumber, IOrganizationContext organizationContext)
   at Microsoft.Crm.Application.InlineEdit.ReadFormDataBuilder..ctor(String recordId, String entityTypeCode, Guid formId, FormFactor formFactor)
   at Microsoft.Crm.Application.Pages.Form.FormDataPage.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.HandleError(Exception e)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at System.Web.UI.Page.ProcessRequest()
   at System.Web.UI.Page.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously): Microsoft Dynamics CRM has experienced an error. Reference number for administrators or support: #E319CBBF</Message>
  <Timestamp>2018-12-06T21:41:24.1001675Z</Timestamp>
  <ExceptionRetriable>false</ExceptionRetriable>
  <ExceptionSource i:nil="true" />
  <InnerFault>
    <ActivityId>4a5ee631-cd38-4751-94ee-10a3f12d6b3f</ActivityId>
    <ErrorCode>-2147220970</ErrorCode>
    <ErrorDetails xmlns:d3p1="http://schemas.datacontract.org/2004/07/System.Collections.Generic" />
    <Message>There was a problem while trying to set value for "DefaultTabId" parameter of the control with ID = notescontrol
One of the following may have caused this exception:
1). The property does not exist on the control or it is not public.
2). The property is not writable.
3). The property is not marked with the CrmControlParameter attribute.</Message>
    <Timestamp>2018-12-06T21:41:24.1001675Z</Timestamp>
    <ExceptionRetriable>false</ExceptionRetriable>
    <ExceptionSource i:nil="true" />
    <InnerFault i:nil="true" />
    <OriginalException i:nil="true" />
    <TraceText i:nil="true" />
  </InnerFault>
  <OriginalException i:nil="true" />
  <TraceText i:nil="true" />
</OrganizationServiceFault>
```

Below is the log from the Attribute Manager
```
Searching for Existing Attribute ncjtc_event.ncjtc_WebpageNeeded
Existing Attribute ncjtc_event.ncjtc_WebpageNeeded found
Searching for Temp Attribute ncjtc_event.ncjtc_WebpageNeeded_t_
Temp Attribute ncjtc_event.ncjtc_WebpageNeeded_t_ not found
Searching for New Attribute ncjtc_event.ncjtc_WebpageNeeded
New Attribute ncjtc_event.ncjtc_WebpageNeeded found
Only an attribute type change has been requested.  Attempting to differentiate between existing and new.
No Temporary Attribute was found.  Treating New as not yet created.
Validating Current CRM State Before Performing Steps:
Beginning Step: Create Temp
Creating Attribute ncjtc_event.ncjtc_WebpageNeeded_t_
Publishing Entity ncjtc_event
Completed Step: Create Temp

Beginning Step: Migrate To Temp
Checking for Calculated Field Dependencies
No Calculated Dependencies Found
Retrieving System Charts with Query: SELECT savedqueryvisualization.savedqueryvisualizationid, savedqueryvisualization.datadescription
FROM savedqueryvisualization
WHERE
( ( ( datadescription Like '%<entity name="ncjtc_event">%name="ncjtc_webpageneeded"%</entity>%' ) 
 Or ( datadescription Like '%<entity name="ncjtc_event">%attribute="ncjtc_webpageneeded"%</entity>%' ) 
) 
) 

Retrieving System Charts with Query: SELECT userqueryvisualization.userqueryvisualizationid, userqueryvisualization.datadescription
FROM userqueryvisualization
WHERE
( ( ( datadescription Like '%<entity name="ncjtc_event">%name="ncjtc_webpageneeded"%</entity>%' ) 
 Or ( datadescription Like '%<entity name="ncjtc_event">%attribute="ncjtc_webpageneeded"%</entity>%' ) 
) 
) 

Retrieving Views with Query: SELECT savedquery.savedqueryid, savedquery.name, savedquery.querytype, savedquery.fetchxml, savedquery.layoutxml
FROM savedquery
WHERE
( ( ( fetchxml Like '%<entity name="ncjtc_event">%name="ncjtc_webpageneeded"%</entity>%' ) 
 Or ( fetchxml Like '%<entity name="ncjtc_event">%attribute="ncjtc_webpageneeded"%</entity>%' ) 
) 
) 

Retrieving Forms with Query: SELECT systemform.formid, systemform.name, systemform.formxml
FROM systemform
WHERE
( systemform.objecttypecode = 'ncjtc_event' And formxml Like '%<control %datafieldname="ncjtc_webpageneeded"%' ) 

Updating Form Information
Checking for Workflow Dependencies
No Workflow Dependencies Found
Checking for Plugin Registration Step Filtering Attribute Dependencies with Query: SELECT sdkmessageprocessingstep.* 
FROM sdkmessageprocessingstep
INNER JOIN sdkmessagefilter on sdkmessageprocessingstep.sdkmessagefilterid = sdkmessagefilter.sdkmessagefilterid
    AND ( sdkmessagefilter.primaryobjecttypecode = 'ncjtc_event' ) 
WHERE
( sdkmessageprocessingstep.stage IN (40, 20, 10) 
And ( ( filteringattributes Like '%,ncjtc_webpageneeded,%' ) 
 Or ( filteringattributes Like 'ncjtc_webpageneeded,%' ) 
 Or ( filteringattributes Like '%,ncjtc_webpageneeded' ) 
 Or ( sdkmessageprocessingstep.filteringattributes = 'ncjtc_webpageneeded' ) 
) 
) 

Checking for Plugin Registration Step Images Attribute Dependencies with Query: SELECT sdkmessageprocessingstepimage.* 
FROM sdkmessageprocessingstepimage
INNER JOIN sdkmessageprocessingstep on sdkmessageprocessingstepimage.sdkmessageprocessingstepid = sdkmessageprocessingstep.sdkmessageprocessingstepid
INNER JOIN sdkmessagefilter on sdkmessageprocessingstep.sdkmessagefilterid = sdkmessagefilter.sdkmessagefilterid
    AND ( sdkmessagefilter.primaryobjecttypecode = 'ncjtc_event' ) 
WHERE
( ( ( attributes Like '%,ncjtc_webpageneeded,%' ) 
 Or ( attributes Like 'ncjtc_webpageneeded,%' ) 
 Or ( attributes Like '%,ncjtc_webpageneeded' ) 
 Or ( sdkmessageprocessingstepimage.attributes = 'ncjtc_webpageneeded' ) 
) 
) 

Publishing Entity ncjtc_event
Checking for Delete Dependencies for ncjtc_event.ncjtc_webpageneeded
Completed Step: Migrate To Temp

Beginning Step: Remove Existing Attribute
Deleting Field ncjtc_event.ncjtc_webpageneeded
Completed Step: Remove Existing Attribute

Beginning Step: Create New Attribute
Creating Attribute ncjtc_event.ncjtc_WebpageNeeded
Publishing Entity ncjtc_event
Completed Step: Create New Attribute

Beginning Step: Migrate To New Attribute
Checking for Calculated Field Dependencies
No Calculated Dependencies Found
Retrieving System Charts with Query: SELECT savedqueryvisualization.savedqueryvisualizationid, savedqueryvisualization.datadescription
FROM savedqueryvisualization
WHERE
( ( ( datadescription Like '%<entity name="ncjtc_event">%name="ncjtc_webpageneeded_t_"%</entity>%' ) 
 Or ( datadescription Like '%<entity name="ncjtc_event">%attribute="ncjtc_webpageneeded_t_"%</entity>%' ) 
) 
) 

Retrieving System Charts with Query: SELECT userqueryvisualization.userqueryvisualizationid, userqueryvisualization.datadescription
FROM userqueryvisualization
WHERE
( ( ( datadescription Like '%<entity name="ncjtc_event">%name="ncjtc_webpageneeded_t_"%</entity>%' ) 
 Or ( datadescription Like '%<entity name="ncjtc_event">%attribute="ncjtc_webpageneeded_t_"%</entity>%' ) 
) 
) 

Retrieving Views with Query: SELECT savedquery.savedqueryid, savedquery.name, savedquery.querytype, savedquery.fetchxml, savedquery.layoutxml
FROM savedquery
WHERE
( ( ( fetchxml Like '%<entity name="ncjtc_event">%name="ncjtc_webpageneeded_t_"%</entity>%' ) 
 Or ( fetchxml Like '%<entity name="ncjtc_event">%attribute="ncjtc_webpageneeded_t_"%</entity>%' ) 
) 
) 

Retrieving Forms with Query: SELECT systemform.formid, systemform.name, systemform.formxml
FROM systemform
WHERE
( systemform.objecttypecode = 'ncjtc_event' And formxml Like '%<control %datafieldname="ncjtc_webpageneeded_t_"%' ) 

Updating Form Information
Checking for Workflow Dependencies
No Workflow Dependencies Found
Checking for Plugin Registration Step Filtering Attribute Dependencies with Query: SELECT sdkmessageprocessingstep.* 
FROM sdkmessageprocessingstep
INNER JOIN sdkmessagefilter on sdkmessageprocessingstep.sdkmessagefilterid = sdkmessagefilter.sdkmessagefilterid
    AND ( sdkmessagefilter.primaryobjecttypecode = 'ncjtc_event' ) 
WHERE
( sdkmessageprocessingstep.stage IN (40, 20, 10) 
And ( ( filteringattributes Like '%,ncjtc_webpageneeded_t_,%' ) 
 Or ( filteringattributes Like 'ncjtc_webpageneeded_t_,%' ) 
 Or ( filteringattributes Like '%,ncjtc_webpageneeded_t_' ) 
 Or ( sdkmessageprocessingstep.filteringattributes = 'ncjtc_webpageneeded_t_' ) 
) 
) 

Checking for Plugin Registration Step Images Attribute Dependencies with Query: SELECT sdkmessageprocessingstepimage.* 
FROM sdkmessageprocessingstepimage
INNER JOIN sdkmessageprocessingstep on sdkmessageprocessingstepimage.sdkmessageprocessingstepid = sdkmessageprocessingstep.sdkmessageprocessingstepid
INNER JOIN sdkmessagefilter on sdkmessageprocessingstep.sdkmessagefilterid = sdkmessagefilter.sdkmessagefilterid
    AND ( sdkmessagefilter.primaryobjecttypecode = 'ncjtc_event' ) 
WHERE
( ( ( attributes Like '%,ncjtc_webpageneeded_t_,%' ) 
 Or ( attributes Like 'ncjtc_webpageneeded_t_,%' ) 
 Or ( attributes Like '%,ncjtc_webpageneeded_t_' ) 
 Or ( sdkmessageprocessingstepimage.attributes = 'ncjtc_webpageneeded_t_' ) 
) 
) 

Publishing Entity ncjtc_event
Checking for Delete Dependencies for ncjtc_event.ncjtc_webpageneeded_t_
Completed Step: Migrate To New Attribute

Beginning Step: Remove Temporary Field
Deleting Field ncjtc_event.ncjtc_webpageneeded_t_
Completed Step: Remove Temporary Field

Steps Completed!
```

**Comment by NakiaDev** [comment]
Same problem happens for us.
If we don't remove the field from the form then it sometimes makes the form unreadable and we gets a similar error.
Sometimes if we don't remove the field from the view makes the Attribute manager fail the steps too.
And now the users reported that Bulk edit forms are not useable neither with a similar error.

**Comment by daryllabar** [comment]
I'd need to know how the form xml is being corrupted..any chance you have a clean version of the form from another environment that you can compare to the corrupted one and let me know?

**Comment by NakiaDev** [comment]
Now both environments works as the same, but when we gonna have this difference again I'll check it then

**Comment by daryllabar** [comment]
Can't recreate
