### ISSUE TITLE
Unable to generate files with latest version installed via XrmToolBox

### ISSUE THREAD

**Issue by squiso** [daryllabar/DLaB.Xrm.XrmToolBoxTools#177]
I've setup a clean install using XrmToolBox. The referenced CrmSvcUtil Ref folder wasn't created in the plugins directory as part of the install so I created the folder and copied the files manually across.

I'm missing the DLaB.CrmSvcUtilExtensions.dll now as highlighted by the below error log.. Should this be handled by the plugin install?

**CrmSvcUtil.log:**
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.NotSupportedException: Could not load provider of type 'DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions'
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: CrmSvcUtil
Method	: CreateInstance
Date	: 4:53:37 PM
Time	: 20/02/2019
Error	: Could not load provider of type 'DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions'
Stack Trace	: at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)

**Comment by daryllabar** [comment]
The Plugin installation should automatically install the crmsvcutil.  I ran into a similar issue today though...  For now, manually download the nuget package from nuget directly, rename it to a zip, and grab the files from there

**Comment by squiso** [comment]
Thanks that did the trick. Cheers for the workaround. I wish I thought of that sooner 👍
