### ISSUE TITLE
Error while creating entities using Xrm Client

### ISSUE THREAD

**Issue by eddie010** [daryllabar/DLaB.Xrm.XrmToolBoxTools#23]
I downloaded the standalone in the latest PreRelease (2016.2.23.2)

When I try to create my entities I check "Use Xrm Client" but once I try to create entities with this option checked, I get an error. I'm connected to my 2015 online project and we're about to update to 2016. We have set up an on prem 2016 project to test this with as well, but without success. I get the same error as below. 

System.TypeInitializationException: The type initializer for 'Microsoft.Xrm.Client.CodeGeneration.CodeCustomization' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Xrm.Client, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Het systeem kan het opgegeven bestand niet vinden.
   at Microsoft.Xrm.Client.CodeGeneration.CodeCustomization..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Xrm.Client.CodeGeneration.CodeCustomization.CustomizeCodeDom(CodeCompileUnit codeUnit, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService.CustomizeCodeDom(CodeCompileUnit codeUnit, IServiceProvider services)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.WriteFile(String outputFile, String language, CodeNamespace codenamespace, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.Microsoft.Crm.Services.Utility.ICodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
Output file was not updated or not found!  
\Plugins\CrmSvcUtil Ref\Entities.cs

**Comment by daryllabar** [comment]
Does the Microsoft.Xrm.Client dll exist in the Plugins\CrmSvcUtil Ref folder?

I switched to the latest version of the CrmSrvcUtil, which uses the Xrm 8.0 dlls, but there is no Microsoft.Xrm.Client dll that uses the 8.0 framework.  I attempted to update the CrmSvcUtil.exe.config to redirect to the 8.0 libraries... But I may have missed something.

**Comment by eddie010** [comment]
The folder only has the Microsoft.Xrm.Client.CodeGeneration.dll

**Comment by daryllabar** [comment]
This has been fixed via 2016.2.29
