### ISSUE TITLE
Single line of text temp attribute length isn't long enough.

### ISSUE THREAD

**Issue by thygesteffensen** [daryllabar/DLaB.Xrm.XrmToolBoxTools#249]
**Tool and Version**
AttributeManager V 1.2019.3.22

**Describe the bug**
When migrate data from old to temp attribute, the length of the new temp attribute isn't considered.

**To Reproduce**
1. Create entity with Single line of text, with length >100
2. Create record with string of length >100
3. Change format of single line of text field to Url.
4. Execute steps

**Expected behavior**
Single line of text field have changed format to Url and data have been moved.

**Screenshots**
Error:
`Beginning Step: Migrate Data To Temp
Retrieving campaign id attribute name
Determining record count (accurate only up to 50000)
Copying data from contoso_msteamschannellink to contoso_msteamschannellink_t_
Copying 1 / 13
System.Exception: A validation error occurred.  The length of the 'conto_msteamschannellink_t_' attribute of the 'campaign' entity exceeded the maximum allowed length of '100'.

TRACE TEXT:

   at DLaB.AttributeManager.Logic.PerformUpdates(IOrganizationService service, OrganizationRequestCollection requests)
   at DLaB.AttributeManager.Logic.CopyData(IOrganizationService service, AttributeMetadata from, AttributeMetadata to, Action actions, Dictionary`2 migrationMapping)
   at DLaB.AttributeManager.Logic.MigrateDataToTemp(Steps stepsToPerform, AttributeMetadata oldAtt, AttributeMetadata tmpAtt, Action actions, Dictionary`2 migrationMapping)
   at DLaB.AttributeManager.Logic.Run(ExecuteStepsInfo info)
   at DLaB.AttributeManager.AttributeManagerPlugin.<>c.<ExecuteSteps>b__34_2(BackgroundWorker w, DoWorkEventArgs e)`

**Additional context**

**Comment by daryllabar** [comment]
Great issue!  Unfortunately I do not have the time in the near future to fix this.  As a work around, you can manually trim anything over the 100 characters and the run the tool for the migration.
