### ISSUE TITLE
XrmToolBox connects to CRM Online, but early bound generation fails to connect

### ISSUE THREAD

**Issue by steveculshaw** [daryllabar/DLaB.Xrm.XrmToolBoxTools#25]
Downloaded the Full zip of of 2016.2.29.1, unblocked it and then unzipped it

Ran XrmToolBox, created a new connection to our CRM Online DEV instance using the unique name URL

Opened the early bound generator

Selected the list of entities to exclude ... the list was populated OK
Added all entities except for the one I was interested in
Then tried to create the code ...

And get an error ... Error	: Connection to CRM is not established. Aborting process.

CRM Authentication Type Detected: OnlineFederation
Executing ... command line deleted ...
CrmSvcUtil : CRM Service Utility [Version 8.0.1.7297]
¸ 2015 Microsoft Corporation. All rights reserved

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Unable to Login to Dynamics CRM
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Connection to CRM is not established. Aborting process.
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: mscorlib
Method	: InvokeMethod
Date	: 17:56:54
Time	: 08/03/2016
Error	: Exception has been thrown by the target of an invocation.
Stack Trace	: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.get_ServiceProvider()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
======================================================================================================================
Inner Exception Level 1	: 
Source	: CrmSvcUtil
Method	: Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata
Date	: 17:56:54
Time	: 08/03/2016
Error	: Connection to CRM is not established. Aborting process.
Stack Trace	: at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)
======================================================================================================================

**Comment by daryllabar** [comment]
Did the deleted command line have the Friendly Org Name URL, or the Unique Org Name URL?

**Comment by steveculshaw** [comment]
Daryl, it had the friendly name in it ... but I had to use the unique name to get my connection to work

**Comment by daryllabar** [comment]
I had this happen locally once. Make sure the URLs in your toolbox config are updated to be the unique named versions.

**Comment by steveculshaw** [comment]
Got it working at home with no proxy issues 
Had to set the <OrganizationServiceUrl> element in mscrmtools2011.config to the unique URL ... actually I set all of them, but after running XrmToolBox, the <OrganizationDataServiceUrl> and <WebApplicationUrl> were changed back to the friendly URL
