### ISSUE TITLE
Error When Attempting to Generate Actions

### ISSUE THREAD

**Issue by jrpetersjr** [daryllabar/DLaB.Xrm.XrmToolBoxTools#263]
EarlyBoundGenerator V 1.2020.4.24

When generating actions I get the following error. 

System.ArgumentException: An entry with the same key already exists.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
   at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.ProjectFile..ctor(List`1 files, Boolean updateProjectFile, VsTfsSourceControlProvider tfs)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteFilesAsync(List`1 files)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.SplitFileByCodeUnit(CodeUnit codeUnit, String filePath, IEnumerable`1 lines)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.Action.CustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
Output file was not updated or not found!

1) Whitelist some actions
2) Generate those actions
3) Whitelist more actions
4) Generate those actions

**Expected behavior**
New Actions should be generated and added to the project.

**Comment by jrpetersjr** [comment]
Figured it out.

**Comment by daryllabar** [comment]
Was it something I did?

**Comment by jrpetersjr** [comment]
Nope. It was a .projitems merge conflict and there were multiple Action.cs references so it was throwing the error.
