### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by RickySaini1** [daryllabar/DLaB.Xrm.XrmToolBoxTools#265]
**Tool and Version**
What tool/version is it that you're reporting a bug for? i.e.
EarlyBoundGenerator V 1.2020.10.2

**Describe the bug**
Getting this error while generating Entities

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Crm.Services.Utility.CodeGenerationService.UpdateAttributeMemberStatements(AttributeMetadata attribute, CodeTypeMember attributeMember)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildAttributeOptionSet(EntityMetadata entity, AttributeMetadata attribute, CodeTypeMember attributeMember, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildEntity(EntityMetadata entity, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildEntities(EntityMetadata[] entityMetadata, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildCodeDom(IOrganizationMetadata organizationMetadata, String outputNamespace, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.Microsoft.Crm.Services.Utility.ICodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
Output file was not updated or not found!  C:\Users\Iqbal Singh\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\Entities.cs

**To Reproduce**
1. Go to  XRMToolBox
2. Click on Early Bound Generator
3. Click on Create Entities

**Expected behavior**
Entitie.cs to be updated with latest schema. It used to work before. Now its throwing an error

**Screenshots**

**Additional context**

**Comment by daryllabar** [comment]
I'm guessing there is something with your metadata that is null that the code is not expecting to be null m. Can you try just creating 1 entity?

**Comment by RickySaini1** [comment]
Yes thanks it looks like Metadata has some issue. I can reproducer the same error using crmsvcutil.exe directly. I have raised a bug with MS.
I can generate selected entities.

**Comment by daryllabar** [comment]
Let me know what MS comes back with

**Comment by pmback** [comment]
Microsoft just fixed this issue in the latest version (9.1.0.68) of Microsoft.CrmSdk.CoreTools nuget.
