### ISSUE TITLE
DirectoryNotFoundException thrown when trying to generate OptionSets from command line

### ISSUE THREAD

**Issue by SigrunO** [daryllabar/DLaB.Xrm.XrmToolBoxTools#27]
I am getting the following exception if I try to generate the code with the command line shown in thte output window. Part of the path seems to get duplicated (see DirectoryNotFoundException) The exception is:

`C:\Users\******\DLaB.Xrm.XrmToolBoxTools-Full\Plugins>"C:\Users\******\DLaB.Xrm.XrmToolBoxTools-Full\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /namespace:"CrmEarlyBound" /out:"C:\Users\******\DLaB.Xrm.XrmToolBoxTools-Full\CrmPackage\Plugins\PrdOptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CreateOptionSetEnums,DLaB.CrmSvcUtilExtensions" /codegenerationservice
:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /
namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /connectionstring:"Url=http://***********;Domain=*****;UserName=sip;Password=******"
CrmSvcUtil : CRM Service Utility [Version 8.0.1.7297]
© 2015 Microsoft Corporation. All rights reserved

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\******\DLaB.Xrm.XrmToolBoxTools-Full\Plugins\Plugins\CrmSvcUtil Ref\alphabets'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at DLaB.CrmSvcUtilExtensions.OptionSet.Transliteration.TransliterationService.<>c.<.cctor>b__7_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at DLaB.CrmSvcUtilExtensions.NamingService.<>c.<Transliterate>b__28_0(LocalizedLabel x)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at DLaB.CrmSvcUtilExtensions.NamingService.Transliterate(OptionMetadata optionMetadata, String defaultName)
   at DLaB.CrmSvcUtilExtensions.NamingService.GetDuplicateNameValues(OptionSetMetadataBase metadata, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.NamingService.AppendValueForDuplicateOptionSetValueNames(OptionSetMetadataBase optionSetMetadata, String name, Nullable`1 value, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.NamingService.GetNameForOption(OptionSetMetadataBase optionSetMetadata, OptionMetadata optionMetadata, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.NamingService.GetNameForOption(OptionSetMetadataBase optionSetMetadata, OptionMetadata optionMetadata, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService.GenerateOptionSet(OptionSetMetadataBase optionSetMetadata, IServiceProvider services)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildAttributeOptionSet(EntityMetadata entity, AttributeMetadata attribute, CodeTypeMember attributeMember, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildEntity(EntityMetadata entity, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildEntities(EntityMetadata[] entityMetadata, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildCodeDom(IOrganizationMetadata organizationMetadata, String outputNamespace, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.Microsoft.Crm.Services.Utility.ICodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, S
tring outputNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider s
ervices)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)`

**Comment by daryllabar** [comment]
Does the path "C:\Users******\DLaB.Xrm.XrmToolBoxTools-Full\Plugins\Plugins\CrmSvcUtil Ref\alphabets" exist for you?

**Comment by SigrunO** [comment]
Yes, the path exists. I just copied the command line from the tool, where the code was generated fine. Bust pasting it to the command line and running it fails with the exception above.

**Comment by SigrunO** [comment]
Sorry, the path C:\Users******\DLaB.Xrm.XrmToolBoxTools-Full\Plugins\Plugins\CrmSvcUtil Ref\alphabets does not exist! 

C:\Users******\DLaB.Xrm.XrmToolBoxTools-Full\Plugins\CrmSvcUtil Ref\alphabets exists...

**Comment by daryllabar** [comment]
This will be fixed in the next release.  As a work around, you *may* be able to run the command line from the same directory as XrmToolBox, and it should still work. 

ie: C:\PathToToolBox>"Plugins\CrmSvcUtil\CrmSvcUtil.exe"
