### ISSUE TITLE
Error when adding splitted files to the .csproj

### ISSUE THREAD

**Issue by xavik0f2** [daryllabar/DLaB.Xrm.XrmToolBoxTools#291]
I have been using a .xml file configuration for awhile successfully. When I re-runned EBG my classes were updated and new classes were added to my visual studio project. I don't know why but now (without modified anything) I get the following error:

```
Splitting File C:···\CrmServiceContext.cs By Code Unit 
**System.ArgumentException: An entry with the same key already exists.**
```

I have a workaround that consists in setting to false the option of adding new classes to vs project. Any idea for solving this?? 
I have tried to change the service context name without success.
Thanks in advance!

**Comment by daryllabar** [comment]
Is there any additional error info?  A line number or something?

**Comment by xavik0f2** [comment]
> Is there any additional error info? A line number or something?

` Ensuring Context File is Accessible 
 Writing file CrmServiceContext.cs to C:\Users\Xavier\AppData\Local\Temp\tmpF018.tmp 
Code written to C:\Users\Xavier\AppData\Local\Temp\tmpF018.tmp.
 Splitting File C:\Dyn365.Componentes\Dyn365.Domain\Domain\Entities\CrmServiceContext.cs By Code Unit 
System.ArgumentException: An entry with the same key already exists.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
   at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.ProjectFile..ctor(List`1 files, Boolean updateProjectFile, VsTfsSourceControlProvider tfs)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteFilesAsync(List`1 files)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.SplitFileByCodeUnit(CodeUnit codeUnit, String filePath, IEnumerable1 lines)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
Output file was not updated or not found!  C:\Dyn365.Componentes\Dyn365.Domain\Domain\Entities\CrmServiceContext.cs
Creation Complete!`

I guess it's here:

![image](https://user-images.githubusercontent.com/9109982/121547895-d8c2de80-ca0c-11eb-9b8b-f9c643999b98.png)


Nope :S, logs file don't persist the error.

**Comment by daryllabar** [comment]
Can I get the temp file: C:\Users\Xavier\AppData\Local\Temp\tmpF018.tmp?

**Comment by daryllabar** [comment]
Looks like it's in the DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.ProjectFile constructor

**Comment by xavik0f2** [comment]
Sure!

[tmpF018.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/6632452/tmpF018.zip)

**Comment by daryllabar** [comment]
The issue is because you have a duplicate `<compile Include=` line in your project file.  I'll fix the tool, but you have a work around of finding the duplicate and removing it.
