### ISSUE TITLE
Unable to convert attribute type to (Local) Option Set

### ISSUE THREAD

**Issue by coolichigo** [daryllabar/DLaB.Xrm.XrmToolBoxTools#294]
AttributeManager V 1.2019.3.22

when trying to convert the attribute type to Local Option Set, it keep getting error when try to execute steps.
![image](https://user-images.githubusercontent.com/86637126/123726447-54f56700-d8d3-11eb-8dd3-29271317b654.png)
![image](https://user-images.githubusercontent.com/86637126/123726471-650d4680-d8d3-11eb-9dc8-8a2d4400581a.png)

Error Message

System.NullReferenceException: Object reference not set to an instance of an object.
   at DLaB.AttributeManager.NewTypeAttributeCreationLogic.CreateOptionSet(OptionSetMetadata optionSet, Nullable`1 defaultFormValue, String formulaDefinition)
   at DLaB.AttributeManager.AttributeManagerPlugin.GetNewAttributeType()
   at DLaB.AttributeManager.AttributeManagerPlugin.ExecuteSteps()
   at XrmToolBox.Extensibility.PluginControlBase.ExecuteMethod(Action action)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by daryllabar** [comment]
Pretty sure I never ended up implementing this as the tool was originally created to convert local to global option sets.  You're free to submit a PR that supports it, or you can manually create the field, and use the steps of the tool to migrate data and the settings so at least you don't have to do that by hand.

**Comment by coolichigo** [comment]
Thanks Daryl, is that means this tool will not wok for converting Two Options to Local Option Set? As that is my initially try but is getting error but it do allow me to change from Two Options to String.

**Comment by daryllabar** [comment]
Anything to a local option set will not work without you manually creating the attribute
