### ISSUE TITLE
Obj Ref Error - Output file was not updated or not found!

### ISSUE THREAD

**Issue by ClintWoods** [daryllabar/DLaB.Xrm.XrmToolBoxTools#295]
After updating to v1.2021.6.14, I am unable to generate any early bound files. For example, on Actions, I have a white list of 5 and blacklist of 64. When running create actions, I get the following error message: 

CRM Authentication Type Detected: None
Tracking Actions Generation Event.
Executing for Actions
Executing "C:\Users\cli2022949\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /generateActions /out:"C:\Projects\crm-mcccd\Plugins\crm-common\CrmSvcUtil Ref\Actions.cs" /namespace:"Xrm" /SuppressGeneratedCodeAttribute /codecustomization:"DLaB.CrmSvcUtilExtensions.Action.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Action.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Action.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /connectionstring:"AuthType=ClientSecret;Url=https://[REDACTED].api.crm.dynamics.com;ClientId=[REDACTED];ClientSecret=*************************[REDACTED] 
CrmSvcUtil : CRM Service Utility [Version 9.1.0.82]
c 2020 Microsoft Corporation. All rights reserved

CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.ConnectToCrmWebService(String crmConnectionString)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient..ctor(String crmConnectionString)
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.CreateOrganizationServiceEndpoint()
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: Microsoft.Xrm.Tooling.Connector
Method	: ConnectToCrmWebService
Date	: 7:14:21 AM
Time	: 7/3/2021
Error	: Object reference not set to an instance of an object.
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.ConnectToCrmWebService(String crmConnectionString)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient..ctor(String crmConnectionString)
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.CreateOrganizationServiceEndpoint()
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
===============================================================

Output file was not updated or not found!  C:\Projects\crm-mcccd\Plugins\crm-common\CrmSvcUtil Ref\Actions.cs
Creation Complete!

**Comment by daryllabar** [comment]
Interesting.  The error is in the actual MS crmsvcutil.exe.    Try running this:

```
"C:\Users\cli2022949\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /generateActions /out:"C:\Projects\crm-mcccd\Plugins\crm-common\CrmSvcUtil Ref\Actions.cs" /namespace:"Xrm" /SuppressGeneratedCodeAttribute /connectionstring:"AuthType=ClientSecret;Url=https://mcccd-dev.api.crm.dynamics.com;ClientId=868cb23d-fcdf-4088-aa5d-3e03d6b20c33;ClientSecret=*************************[REDACTED]
```

With your actual Client Secret and see if that works.  (It will generate different entities because it won't include any EBG customizations, but it will verify that the CrmSvcUtil can connect without the EBG logic) If it doesn't, it's an issue with the CrmSvcUtil and you should open a ticket with MS.  If it does, let me know and I'll re-open this.

**Comment by ClintWoods** [comment]
Same results. I'll see about updating the sdk, therefore crmsvcutil

**Comment by daryllabar** [comment]
Yep, if you find a version of the SDK that works, then let me know.   Regardless you should be opening a support request with Microsoft
