### ISSUE TITLE
Unable to generate classes as trying to connect to Office 365

### ISSUE THREAD

**Issue by pstather** [daryllabar/DLaB.Xrm.XrmToolBoxTools#30]
Hello,
Apologies, this is based on #24 
I was unable to respond before the thread was closed, so here goes.
When I run the Early bound generator, I get the below message
When I run the tool, I get the below

CRM Authentication Type Detected: Federation
Executing "C:\Users\philst\Downloads\XrmToolBox\Plugins\CrmSvcUtil Ref\crmsvcutil.exe" /url:"/XRMServices/2011/Organization.svc" /namespace:"Core.Crm" /out:"C:\Users\philst\Downloads\CrmContext.cs" /servicecontextname:"CrmContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /username:"" /password:"**********" 
CrmSvcUtil : CRM Service Utility [Version 8.0.1.7297]
¸ 2015 Microsoft Corporation. All rights reserved

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Exception while trying to connect Discovery Server, (North America) URI is = https://disco.crm.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Exception while trying to connect Discovery Server, (Europe, Middle East and Africa) URI is = https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Exception while trying to connect Discovery Server, (Asia Pacific Area) URI is = https://disco.crm5.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Exception while trying to connect Discovery Server, (South America) URI is = https://disco.crm2.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Exception while trying to connect Discovery Server, (Oceania) URI is = https://disco.crm6.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Exception while trying to connect Discovery Server, (Japan) URI is = https://disco.crm7.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Exception while trying to connect Discovery Server, (North America 2) URI is = https://disco.crm9.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Exception while trying to connect Discovery Server, (Canada) URI is = https://disco.crm3.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Exception while trying to connect Discovery Server, (India) URI is = https://disco.crm8.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : No Orgs Found, Searched Online. Region Setting = 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Unable to Login to Dynamics CRM
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Connection to CRM is not established. Aborting process.
at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()
at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstanceTIService
at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source : mscorlib
Method : InvokeMethod
Date : 10:49:49
Time : 22/03/2016
Error : Exception has been thrown by the target of an invocation.
Stack Trace : at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.Crm.Services.Utility.ServiceFactory.CreateInstanceTIService
at Microsoft.Crm.Services.Utility.ServiceProvider.InitializeServices(CrmSvcUtilParameters parameters)
at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()

at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)

Inner Exception Level 1 : 
Source : CrmSvcUtil
Method : Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata
Date : 10:49:49
Time : 22/03/2016
Error : Connection to CRM is not established. Aborting process.
Stack Trace : at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.Microsoft.Crm.Services.Utility.IMetadataProviderService.LoadMetadata()

at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService..ctor(IMetadataProviderService defaultService, IDictionary`2 paramters)

Output file was not updated or not found! C:\Users\philst\Downloads\CrmContext.cs

Apologies for the delay and thank you

**Comment by daryllabar** [comment]
Your Url is listed as 

> /url:"/XRMServices/2011/Organization.svc"

I'm assuming you obfuscated it?

Can you make sure that it is showing the unique Org name, rather than the human readable version  (https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/issues/21)

**Comment by pstather** [comment]
Hello,
The url is https://mdinsurancetest.mdins.co.uk

**Comment by daryllabar** [comment]
So it the url parameter coming through as 

> /url:"https://mdinsurancetest.mdins.co.uk/XrmServices/2011/Organization.svc" ?

**Comment by pstather** [comment]
Yes, that is correct, sorry

**Comment by daryllabar** [comment]
Can you create a test user name and password for me to attempt to login with to trouble shoot?

**Comment by daryllabar** [comment]
You could also try to run the command line manually, and see if you can see if something isn't right.

**Comment by daryllabar** [comment]
Any Update on this?

**Comment by Djurman** [comment]
Try changing the below values to Off in the crmsvcutil.config:
<add name="Microsoft.Xrm.Tooling.CrmConnectControl" value="Off"/>
<add name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" value="Off"/>
<add name="CrmSvcUtil" value="Off"/>

**Comment by Djurman** [comment]
Change the below values to Off in the crmsvcutil.config and then it should work:
`
<add name="Microsoft.Xrm.Tooling.CrmConnectControl" value="Off"/>
<add name="Microsoft.Xrm.Tooling.Connector.CrmServiceClient" value="Off"/>
<add name="CrmSvcUtil" value="Off"/>`

**Comment by daryllabar** [comment]
@Djurman, do you have a link to documentation around what those things are, or what they do, or why it helps?

**Comment by daryllabar** [comment]
No Response.  Closing

**Comment by mporter45042** [comment]
I was having the same issue and Djurman's response above worked to fix my issue. Just wanted to follow up in case anyone else had this issue.

**Comment by daryllabar** [comment]
@mporter45042  are you on the newest version of the EBG?

**Comment by mporter45042** [comment]
I am not 100% sure, how can I validate that for you?

Michael Porter
Senior Developer | Health Carousel
t: 513.458.2566 | m: 937.510.2329
michael.porter@healthcarousel.com<mailto:michael.porter@healthcarousel.com>

**Comment by daryllabar** [comment]
On the plugin store, you should be searching for Early Bound Generator, it used to be "DLaB tools" but it is now separate.  Latest and greatest is 1.2016.12.29

**Comment by marcesepu** [comment]
The error appear again! 
I've tried in diferent evironment and tenants.

CRM Authentication Type Detected: OnlineFederation
Executing for Entities
Executing "C:\Users\*******\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://**********.api.crm4.dynamics.com/XRMServices/2011/Organization.svc" /namespace:"Actio_Esri_Dynamics.Shared.EarlyBound" /out:"C:\**********\Xrm.cs" /servicecontextname:"XrmServiceContext" /codecustomization:"DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Entity.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Entity.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService,DLaB.CrmSvcUtilExtensions" /username:"***************" /password:"**************" 
CrmSvcUtil : CRM Service Utility [Version 9.0.0.9479]
¸ 2017 Microsoft Corporation. All rights reserved

CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.InvalidOperationException: Unable to initialize the native configuration support external to the web worker process (HRESULT=0x80040154).
nativerd.dll must be in %windir%\system32\inetsrv.
   at System.Web.Configuration.ProcessHostConfigUtils.NativeConfigWrapper..ctor()
   at System.Web.Configuration.ProcessHostConfigUtils.InitStandaloneConfig()
   at System.Web.Configuration.ProcessHostMapPath..ctor(IProcessHostSupportFunctions functions)
   at System.Web.Configuration.IISMapPath.GetInstance()
   at System.Web.Configuration.WebConfigurationHost.ChooseAndInitConfigMapPath(Boolean useConfigMapPath, IConfigMapPath configMapPath, ConfigurationFileMap fileMap)
   at System.Web.Configuration.WebConfigurationHost.InitForConfiguration(String& locationSubPath, String& configPath, String& locationConfigPath, IInternalConfigRoot configRoot, Object[] hostInitConfigurationParams)
   at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.Internal.InternalConfigConfigurationFactory.System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Web.Configuration.WebConfigurationHost.OpenConfiguration(WebLevel webLevel, ConfigurationFileMap fileMap, VirtualPath path, String site, String locationSubPath, String server, String userName, String password, IntPtr tokenHandle)
   at System.Web.Hosting.HostingEnvironment.get_CacheStoreProviderSettings()
   at System.Web.Caching.Cache.GetObjectCache(Boolean createIfDoesNotExist)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetCachedCRMService(CrmWebSvc& ConnectionObject)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.IntilizeService(CrmWebSvc& ConnectionObject)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CreateCRMWebServiceConnection(OrganizationServiceProxy externalOrgServiceProxy, AuthenticationType requestedAuthType, String hostName, String port, String orgName, NetworkCredential credential, String userId, SecureString password, String domain, String CrmOnlineRegion, String claimsHomeRealm, Boolean useSsl, Boolean useUniqueInstance, OrganizationDetail orgDetail, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, OrganizationWebProxyClient externalOrgWebProxyClient, String certificateThumbPrint, StoreName certificateStoreName, X509Certificate2 certificate, Uri instanceUrl, Boolean isCloned)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.ConnectToCrmWebService(String crmConnectionString)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient..ctor(String crmConnectionString)
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.CreateOrganizationServiceEndpoint()
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: System.Web
Method	: .ctor
Date	: 2:34:23 PM
Time	: 8/8/2019
Error	: Unable to initialize the native configuration support external to the web worker process (HRESULT=0x80040154).
nativerd.dll must be in %windir%\system32\inetsrv.
Stack Trace	: at System.Web.Configuration.ProcessHostConfigUtils.NativeConfigWrapper..ctor()
   at System.Web.Configuration.ProcessHostConfigUtils.InitStandaloneConfig()
   at System.Web.Configuration.ProcessHostMapPath..ctor(IProcessHostSupportFunctions functions)
   at System.Web.Configuration.IISMapPath.GetInstance()
   at System.Web.Configuration.WebConfigurationHost.ChooseAndInitConfigMapPath(Boolean useConfigMapPath, IConfigMapPath configMapPath, ConfigurationFileMap fileMap)
   at System.Web.Configuration.WebConfigurationHost.InitForConfiguration(String& locationSubPath, String& configPath, String& locationConfigPath, IInternalConfigRoot configRoot, Object[] hostInitConfigurationParams)
   at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.Internal.InternalConfigConfigurationFactory.System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Web.Configuration.WebConfigurationHost.OpenConfiguration(WebLevel webLevel, ConfigurationFileMap fileMap, VirtualPath path, String site, String locationSubPath, String server, String userName, String password, IntPtr tokenHandle)
   at System.Web.Hosting.HostingEnvironment.get_CacheStoreProviderSettings()
   at System.Web.Caching.Cache.GetObjectCache(Boolean createIfDoesNotExist)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetCachedCRMService(CrmWebSvc& ConnectionObject)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.IntilizeService(CrmWebSvc& ConnectionObject)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CreateCRMWebServiceConnection(OrganizationServiceProxy externalOrgServiceProxy, AuthenticationType requestedAuthType, String hostName, String port, String orgName, NetworkCredential credential, String userId, SecureString password, String domain, String CrmOnlineRegion, String claimsHomeRealm, Boolean useSsl, Boolean useUniqueInstance, OrganizationDetail orgDetail, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, OrganizationWebProxyClient externalOrgWebProxyClient, String certificateThumbPrint, StoreName certificateStoreName, X509Certificate2 certificate, Uri instanceUrl, Boolean isCloned)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.ConnectToCrmWebService(String crmConnectionString)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient..ctor(String crmConnectionString)
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.CreateOrganizationServiceEndpoint()
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.Entity.MetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
======================================================================================================================

Output file was not updated or not found!  C:\************\Xrm.cs
Creation Complete!

**Comment by daryllabar** [comment]
can you connect with the plugin registration tool from the SDK?

**Comment by marcesepu** [comment]
> can you connect with the plugin registration tool from the SDK?

Yes

**Comment by marcesepu** [comment]
Hello @daryllabar, 

I've setted the crmsvcutil.config in verbose mode, and I've saw that was an error with nativerd.dll
I've fixed the error reading this post: https://github.com/MscrmTools/XrmToolBox/issues/778

Thanks for your support.
best regards

**Comment by yangs2016** [comment]
Got this error while running CrmSvcUtil.exe to generate the early bound classes that I used to be able to, complaining about service url not parsed, 
"Exiting Microsoft.Crm.Services.Utility.ICommandLineArgumentSource.OnInvalidArgument: Found string https://mycrm.mydomain.com/devcrm/xrmservices/2011/organization.svc in arguments array that could not be parsed."

Here is the command line (substitute sensitive fields with dummy value):
CrmSvcUtil.exe /out: crmproxyclasses.cs /url: https://dynamics365.mydomain.com/devcrm/xrmservices/2011/organization.svc /domain:mydomain /username:uid /password:pwd /namespace:MyCo.DynamicsCrm.Contracts.Proxy /serviceContextName:CrmProxyContext

I used this command without problem in the past (before upgrading to Dynamics 365).

**Comment by daryllabar** [comment]
@yangs2016 can you create a separate issue?  Also, what do you mean by 

(before upgrading to Dynamics 365). What version number did you jump to/from.  Did you change authentication?  ADFS vs AD?

**Comment by yangs2016** [comment]
No, no change in authentication. Actually, I just tried to remove part xrmservices/2011/organization.svc and it worked now: 

The command that works is like this:
CrmSvcUtil.exe /out: crmproxyclasses.cs /url: https://dynamics365.mydomain.com/devcrm /domain:mydomain /username:uid /password:pwd /namespace:MyCo.DynamicsCrm.Contracts.Proxy /serviceContextName:CrmProxyContext

@daryllabar Since I wasn't involved in the IT upgrades of our on-premise Dynamics CRM, sorry I can tell what versions before the update. But looks like the latest version does not like having the service url spelled out like before, i.e., https://dynamics365.mydomain.com/devcrm/ **xrmservices/2011/organization.svc** was fine a few upgrades back but now only **https://dynamics365.mydomain.com/devcrm** is accepted.
