### ISSUE TITLE
ClientSecret connection string errors on api request

### ISSUE THREAD

**Issue by jblaseske** [daryllabar/DLaB.Xrm.XrmToolBoxTools#315]
**Tool and Version**
1.2022.4.3

**Describe the bug**
Getting a login error using Client/Secret connection string:
"Invalid Login Information : The HTTP request was forbidden with client authentication scheme 'Anonymous'.
The HTTP request was forbidden with client authentication scheme 'Anonymous'. => The remote server returned an error: (403) Forbidden.Unable to Login to Dynamics CRM
Unable to Login to Dynamics CRM"

**To Reproduce**
Using XrmToolbox, Open the Early Bound Generator using a connection created with a Client/Secret connection string

**Expected behavior**
Tool should be able to log in using a client/secret connection, especially now that Office365 has been fully deprecated in most D365 online instances.

**Comment by daryllabar** [comment]
I'm not having any issue with this.  What is the command line that it is attempting to run?

**Comment by jblaseske** [comment]
Connection was created (successfully) in XrmToolbox connections using a QueryString of the type:  "Url=<orgurl>; ClientId=<ClientId>; ClientSecret=<ClientSecret>; AuthType=ClientSecret;"

It gives the above error and then defaults to the pop-up authentication login.

This happens on any attempt to generate Entities, Option Sets, or Actions.

**Comment by daryllabar** [comment]
Did you get that query string from the XTB connections?  I was asking for the command like that spits out in the output text box of the EBG when you attempt to generate something

**Comment by jblaseske** [comment]
The QueryString was not generated by an XTB interface.  It was simply entered using the XTB QueryString connection option.

Here is the entire content of the EBG log:

CRM Authentication Type Detected: None
Tracking OptionSets Generation Event.
Executing for OptionSets
Executing "C:\Users\jblaeske\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://jddealerdevcodevltest.api.crm.dynamics.com" /namespace:"CrmEarlyBound" /SuppressGeneratedCodeAttribute /out:"C:\Users\jblaeske\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" 
CrmSvcUtil : CRM Service Utility [Version 9.1.0.95]
c 2020 Microsoft Corporation. All rights reserved

Begin Reading Metadata
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : ERROR REQUESTING Token FROM THE Authentication context - USER intervention required but not permitted by prompt behavior
Source	: Microsoft.IdentityModel.Clients.ActiveDirectory
Method	: VerifyAuthorizationResult
Date	: 4/14/2022
Time	: 7:24:46 AM
Error	: AADSTS16000: Either multiple user identities are available for the current request or selected account is not supported for the scenario.
Trace ID: cb2ee1d4-5c82-4c08-b0e3-907569b02500
Correlation ID: 4ca12f4e-05e3-4c0d-8fbf-0f1fbc59c1d1
Timestamp: 2022-04-14 12:24:46Z
Stack Trace	: at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.VerifyAuthorizationResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenInteractiveHandler.<PreTokenRequestAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__28.MoveNext()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to connect to CRM: AADSTS16000: Either multiple user identities are available for the current request or selected account is not supported for the scenario.
Trace ID: cb2ee1d4-5c82-4c08-b0e3-907569b02500
Correlation ID: 4ca12f4e-05e3-4c0d-8fbf-0f1fbc59c1d1
Timestamp: 2022-04-14 12:24:46Z
Source	: Microsoft.IdentityModel.Clients.ActiveDirectory
Method	: VerifyAuthorizationResult
Date	: 4/14/2022
Time	: 7:24:46 AM
Error	: AADSTS16000: Either multiple user identities are available for the current request or selected account is not supported for the scenario.
Trace ID: cb2ee1d4-5c82-4c08-b0e3-907569b02500
Correlation ID: 4ca12f4e-05e3-4c0d-8fbf-0f1fbc59c1d1
Timestamp: 2022-04-14 12:24:46Z
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ProcessAdalExecption(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier& user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, CrmLogEntry logSink, Boolean useDefaultCreds, String& authToken, AdalException adalEx)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ExecuteAuthenticateServiceProcess(Uri serviceUrl, ClientCredentials clientCredentials, X509Certificate2 userCert, UserIdentifier user, String clientId, Uri redirectUri, PromptBehavior promptBehavior, String tokenCachePath, Boolean isOnPrem, String authority, Uri& targetServiceUrl, AuthenticationContext& authContext, String& resource, UserIdentifier& userIdent, CrmLogEntry logSink, Boolean useDefaultCreds, SecureString clientSecret)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ConnectAndInitCrmOrgService(OrganizationDetail orgdata, Boolean IsOnPrem, Uri homeRealmUri)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DoDirectLogin(Boolean IsOnPrem)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 4/14/2022
Time	: 7:24:46 AM
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided
======================================================================================================================

ERROR REQUESTING Token FROM THE Authentication context - USER intervention required but not permitted by prompt behavior
AADSTS16000: Either multiple user identities are available for the current request or selected account is not supported for the scenario.
Trace ID: cb2ee1d4-5c82-4c08-b0e3-907569b02500
Correlation ID: 4ca12f4e-05e3-4c0d-8fbf-0f1fbc59c1d1
Timestamp: 2022-04-14 12:24:46ZUnable to connect to CRM: AADSTS16000: Either multiple user identities are available for the current request or selected account is not supported for the scenario.
Trace ID: cb2ee1d4-5c82-4c08-b0e3-907569b02500
Correlation ID: 4ca12f4e-05e3-4c0d-8fbf-0f1fbc59c1d1
Timestamp: 2022-04-14 12:24:46Z
AADSTS16000: Either multiple user identities are available for the current request or selected account is not supported for the scenario.
Trace ID: cb2ee1d4-5c82-4c08-b0e3-907569b02500
Correlation ID: 4ca12f4e-05e3-4c0d-8fbf-0f1fbc59c1d1
Timestamp: 2022-04-14 12:24:46ZUnable to Login to Dynamics CRM
Unable to Login to Dynamics CRM
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Exception: Connection to CRM is not established. Aborting process.
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: CrmSvcUtil
Method	: LoadMetadata
Date	: 7:24:46 AM
Time	: 4/14/2022
Error	: Connection to CRM is not established. Aborting process.
Stack Trace	: at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
======================================================================================================================

Unable to login.  Attempting to login using interactive mode.
Executing "C:\Users\jblaeske\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /url:"https://jddealerdevcodevltest.api.crm.dynamics.com" /namespace:"CrmEarlyBound" /SuppressGeneratedCodeAttribute /out:"C:\Users\jblaeske\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\OptionSets.cs" /codecustomization:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.OptionSet.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /namingservice:"DLaB.CrmSvcUtilExtensions.NamingService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /interactivelogin:true 
CrmSvcUtil : CRM Service Utility [Version 9.1.0.95]
c 2020 Microsoft Corporation. All rights reserved

Begin Reading Metadata
User aborted Login
CrmSvcUtil Error: 2 : Exiting program with exit code 2 due to exception : System.Exception: Connection to CRM is not established. Aborting process.
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: CrmSvcUtil
Method	: LoadMetadata
Date	: 7:24:51 AM
Time	: 4/14/2022
Error	: Connection to CRM is not established. Aborting process.
Stack Trace	: at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)
======================================================================================================================

Output file was not updated or not found!  C:\Users\jblaeske\AppData\Roaming\MscrmTools\XrmToolBox\Settings\EBG\OptionSets.cs
Creation Complete!

**Comment by daryllabar** [comment]
#352 will resolve this when it goes live.
