### ISSUE TITLE
Object Reference Not Set to Instance of Object after using clientid/secret connection?

### ISSUE THREAD

**Issue by ClintWoods** [daryllabar/DLaB.Xrm.XrmToolBoxTools#333]
EarlyBoundGenerator V 1.2022.5.3

for Entities, OptionSets and Actions all looks normal:
Executing "C:\Users\cli2022949\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator\crmsvcutil.exe" /generateActions /out:"C:\Projects\_clientnamehere_\Plugins\crm-common\CrmSvcUtil Ref\Actions.cs" /namespace:"Xrm" /SuppressGeneratedCodeAttribute /codecustomization:"DLaB.CrmSvcUtilExtensions.Action.CustomizeCodeDomService,DLaB.CrmSvcUtilExtensions" /codegenerationservice:"DLaB.CrmSvcUtilExtensions.Action.CustomCodeGenerationService,DLaB.CrmSvcUtilExtensions" /codewriterfilter:"DLaB.CrmSvcUtilExtensions.Action.CodeWriterFilterService,DLaB.CrmSvcUtilExtensions" /metadataproviderservice:"DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService,DLaB.CrmSvcUtilExtensions" /connectionstring:"AuthType=ClientSecret;Url=https:/_clientnamehere_.api.crm.dynamics.com;ClientId=clientIdGoes Here;ClientSecret=***************************" 

But for all three I see:
CrmSvcUtil Error: 2 : ===== DETAIL ======
CrmSvcUtil Error: 2 : Source	: Microsoft.Xrm.Tooling.Connector
Method	: ConnectToCrmWebService
Date	: 9:09:06 AM
Time	: 9/6/2022
Error	: Object reference not set to an instance of an object.
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.ConnectToCrmWebService(String crmConnectionString)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient..ctor(String crmConnectionString)
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.CreateOrganizationServiceEndpoint()
   at Microsoft.Crm.Services.Utility.SdkMetadataProviderService.LoadMetadata()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadataInternal()
   at DLaB.CrmSvcUtilExtensions.BaseMetadataProviderService.LoadMetadata()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Run()
   at Microsoft.Crm.Services.Utility.CrmSvcUtil.Main(String[] args)

This only happens for this particular client of mine. No idea what is different here. Per a previous chat (more than a year ago) with you, the client opened a ticket with MSFT who would (of course) only support crmsvcutil.exe. They were able to execute crmsvcutile.exe successfully by adding the /il parameter as they are using MFA.  So, crmsvcutil works and I hit a dead end. Note I tried changing the output folder to a 'generic' location (not under .../users/...) just in case it was a write access issue. I do see the three files in that directory, but they are 0 bytes. So, it sees the output directory and can create the files. They just never get populated.

The expected outcome is to have the Actions.cs, Entities.cs and Actions.cs populated as normal. This tool has been working for this client for years. I think the change happened when we changed to clientid/secret connections. 

![image](https://user-images.githubusercontent.com/67845398/188689648-2888f177-9aff-490e-963d-bc06c27d7d16.png)

**Comment by ClintWoods** [comment]
Just an additional note: I renamed the client's DLaB.EarlyBoundGenerator.DefaultSettings.xml file so it created a new one. Same error. Since this error is specific to the client's D365 instance that was the only thing I could think of that would differ from my other clients who are not having this issue.

**Comment by daryllabar** [comment]
@ClintWoods The /IL requests an interactive login.  Does this command line generate the login and they are able to provide the correct information?  Or does it magically allow it to work, without the login, but by adding it, it works?

**Comment by ClintWoods** [comment]
when /il is used, the Users is prompted to enter the password via a dialog that pops up. no problems with MFA. After this it generates our OptionSets.cs and Actions.cs but not Entities.cs using our whitelist settings.

**Comment by ClintWoods** [comment]
so, a 2/3's workaround... unfortunately we need entities.cs as well.

**Comment by daryllabar** [comment]
You're getting an ArgumentOutOfRangeException?  Interesting.  I haven't had any issues with client id/secret.  Any chance the client doesn't have a Dataverse role?  Can I get access to a set of credentials to test with?

**Comment by ClintWoods** [comment]
Mornin' @daryllabar. It definitely has a Role. I use the same for SSIS jobs and all the other tools in XrmToolbox. I will float the idea of setting up a new you can test with but I don't expect that it will happen. We'd be exposing some PII in a vertical that is very sensitive to that. Still very early hear. I'll ping you when I hear back. Is there another approach we can take? Teams screen share? anything...

**Comment by ClintWoods** [comment]
hi @daryllabar. Definitely a no-go for direct access for anyone outside the organization. Is there an alternate approach we can take? screen share? something...

**Comment by daryllabar** [comment]
We could probably do a screen share.  Can you send me a message on LinkedIn or Twitter and we'll setup a time?

**Comment by ClintWoods** [comment]
Just sent you a message from Linked In

**Comment by daryllabar** [comment]
Not sure why they were unable to login, but here is the error that was occurring for entities:

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.Collections.CollectionBase.System.Collections.IList.get_Item(Int32 index)
at System.CodeDom.CodeTypeReferenceCollection.get_Item(Int32 index)
at DLaB.CrmSvcUtilExtensions.Extensions.IsContextType(CodeTypeDeclaration type)
at DLaB.CrmSvcUtilExtensions.Entity.MultiOptionSetAttributeUpdater.CustomizeCodeDom(CodeCompileUnit codeUnit, IServiceProvider services)
at DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService.CustomizeCodeDom(CodeCompileUnit codeUnit, IServiceProvider services)
at Microsoft.Crm.Services.Utility.CodeGenerationService.WriteFile(String outputFile, String language, CodeNamespace codenamespace, ServiceProvider serviceProvider, Boolean writeProxyAttrib, Boolean isFileSplit)
at Microsoft.Crm.Services.Utility.CodeGenerationService.Microsoft.Crm.Services.Utility.ICodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
```
