### ISSUE TITLE
`pac` fails with `Could not load provider of type 'DLaB.ModelBuilderExtensions.CodeWriterFilterService,DLaB.ModelBuilderExtensions'`

### ISSUE THREAD

**Issue by skfd** [daryllabar/DLaB.Xrm.XrmToolBoxTools#396]
**Tool and Version**
EarlyBoundGenerator V 2.2023.4.6

**Describe the bug**
Running the pac command from terminal fails with error below.

I am trying to attach the debugger to extension to maybe catch the previous issue i have, but can't figure out how to run `pac` correctly...

**To Reproduce**
1. Copy paste pac command from Early Bound Generator v2 log. See below

**Output**
```
PS C:\Users\skfd\AppData\Roaming\MscrmTools\XrmToolBox\Plugins\DLaB.EarlyBoundGenerator> PAC modelbuilder build --outdirectory "C:\Users\skfd\Code\CRM\solutions\project\plugin-src\project.Plugins" --settingsTemplateFile "C:\Users\skfd\Code\CRM\solutions\project\plugin-src\project.Plugins\builderSettings.json"
Microsoft PowerPlatform CLI
Version: 1.21.13+g348c5e9

Error: Model generation failed.
System.NotSupportedException: Could not load provider of type 'DLaB.ModelBuilderExtensions.CodeWriterFilterService,DLaB.ModelBuilderExtensions'
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ServiceFactory.CreateInstance[TIService](TIService defaultServiceInstance, String parameterValue, ModelBuilderInvokeParameters parameters)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ServiceProvider.InitializeServices(ModelBuilderInvokeParameters parameters)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ProcessModelInvoker.get_ServiceProvider()
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ProcessModelInvoker.get_IsLiveConnectionRequired()
   at bolt.module.modelbuilder.verbs.ModelBuilderVerb.Execute(IContext context, Command command)
```

**Comment by daryllabar** [comment]
I should probably add instructions.  You'll need to copy the DLaB. ModelbuilderExtensions.dll and files from the DLaB.EarlyblundGeneratorV2 folder to the PAC directory.

**Comment by daryllabar** [comment]
https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/Integrating-The-Early-Bound-Generator-Into-Your-Build-Pipeline
