### ISSUE TITLE
Exception on generating model with Model Builder V2 nuget

### ISSUE THREAD

**Issue by otishone** [daryllabar/DLaB.Xrm.XrmToolBoxTools#407]
I am using the latest nuget package DLaB.Xrm.EarlyBoundGeneratorV2 (2.2023.4.17) for model generation with the newest Microsoft.PowerApps.CLI package (version 1.22.2).
When I am invoking the model generation with a settings file I have an error as below.
When I am reverting the CLI version to [1.21.13](https://www.nuget.org/packages/Microsoft.PowerApps.CLI/1.21.13) everything works filne.

I am invoking the tool as described here: https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/Integrating-The-Early-Bound-Generator-Into-Your-Build-Pipeline#running-via-the-command-line-pac

`System.NotSupportedException: Unable to lookup static field ModelBuilderLogger of type Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ProcessModelInvoker!
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.InvokePublicInstanceMethodOnNonPublicStaticField[TStaticFieldType](String fieldName, String methodName, Object[] parameters)
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.ProcessModelInvoker_ModelBuilderLogger_TraceMethodStart(String message, Object[] messageData)
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider serviceProvider)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)

Exiting program with exception: Unable to lookup static field ModelBuilderLogger of type Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ProcessModelInvoker!
DataverseModelBuilderLib Error: 2 : Exiting program with exit code 2 due to exception : System.NotSupportedException: Unable to lookup static field ModelBuilderLogger of type Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ProcessModelInvoker!
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.InvokePublicInstanceMethodOnNonPublicStaticField[TStaticFieldType](String fieldName, String methodName, Object[] parameters)
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.ProcessModelInvoker_ModelBuilderLogger_TraceMethodStart(String message, Object[] messageData)
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider serviceProvider)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ProcessModelInvoker.WriteCode(IOrganizationMetadata organizationMetadata)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ProcessModelInvoker.Run()
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ProcessModelInvoker.Invoke(IOrganizationService dvService)
DataverseModelBuilderLib Error: 2 : ===== DETAIL ======
DataverseModelBuilderLib Error: 2 : Source      : DLaB.ModelBuilderExtensions
Method  : InvokePublicInstanceMethodOnNonPublicStaticField
Date    : 13:21:27
Time    : 20.04.2023
Error   : Unable to lookup static field ModelBuilderLogger of type Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ProcessModelInvoker!
Stack Trace     : at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.InvokePublicInstanceMethodOnNonPublicStaticField[TStaticFieldType](String fieldName, String methodName, Object[] parameters)
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.ProcessModelInvoker_ModelBuilderLogger_TraceMethodStart(String message, Object[] messageData)
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider serviceProvider)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ProcessModelInvoker.WriteCode(IOrganizationMetadata organizationMetadata)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ProcessModelInvoker.Run()
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ProcessModelInvoker.Invoke(IOrganizationService dvService)
======================================================================================================================`

**Comment by daryllabar** [comment]
Thanks for being my canary in the coal mine!

**Comment by daryllabar** [comment]
hmm... The Microsoft.PowerPlatform.Dataverse.ModelBuilderLib doesn't have a new version.  This means that I can't (easily?) upgrade the EBG so that it works with both the Microsoft.PowerPlatform.Dataverse.ModelBuilderLib and the newest PAC CLI.  I'll see if I can get Microsoft to get me an update.

Curious, are you using the EBG nuget or the EBG API nuget?

**Comment by otishone** [comment]
As I wrote before I've used the instructions from [here](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/issues/407), to setup the script, so I used EBGV2 nuget instead of the API one. If You think the API one should be a better choice I can try it, if the configuration will look the same, that would be a quick check :).

**Comment by daryllabar** [comment]
I'm a little slower on releasing the API, so if what I wrote works, then I'd stick to that.  I see Microsoft releases the new modelbuilder nuget.  I'll see if I can get this fixed today.

**Comment by daryllabar** [comment]
New version should resolve this issue for you.
