### ISSUE TITLE
Splitting Actions fails

### ISSUE THREAD

**Issue by rappen** [daryllabar/DLaB.Xrm.XrmToolBoxTools#440]
We only have standard Actions, no changed in the settings, but this always happens:

```
Begin Reading Metadata
Completed Reading Metadata 00:00:37.3538378
Begin Writing File
 Ensuring Context File is Accessible 
 Writing file Actions.cs to C:\Users\JonasRapp\AppData\Local\Temp\tmp7F1D.tmp 
Processing 124 OptionSets
Wrote 0 OptionSets
Processing 586 Entities
Wrote 0 Entities
Processing 954 Messages
Wrote 488 Messages
Code written to C:\Users\JonasRapp\AppData\Local\Temp\tmp7F1D.tmp.
 Splitting File C:\Dev\CRMK\Socialdemokraterna\Socialdemokraterna\Development\Back-end\Shared\EarlyBound\Dataverse\Actions\Actions.cs By Code Unit 
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.SplitFileByCodeUnit(CodeUnit codeUnit, String filePath, IEnumerable`1 lines)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.Action.CustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
Completed Writing File 00:00:00.2368293
Output file was not updated or not found!  C:\Dev\CRMK\Socialdemokraterna\Socialdemokraterna\Development\Back-end\Shared\EarlyBound\Dataverse\Actions\Actions.cs
```

**_Illegal characters in path._**

Doing it with *Create One File Per Action: False* it works fine.

---
- Deployment: Online
- DB Version: 9.2.23073.170
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.6.65
- Tool Version: 1.2022.9.22

**Comment by daryllabar** [comment]
Have you tried the early bound generator V2?  It's a new tool in the tool box.

**Comment by rappen** [comment]
No, sorry.
Same settings, same result etc?
Or would we need to change stuffs in our code?

**Comment by daryllabar** [comment]
It should be a seemless upgrade.  You'll just need to select the same configuration XML file that the V1 uses.  If there are issues with the transition, let me know.  I'm currently not planning on updating V1.
