### ISSUE TITLE
"Delete Files from Output folders" fails if "Generate Messages" = False

### ISSUE THREAD

**Issue by eleung83** [daryllabar/DLaB.Xrm.XrmToolBoxTools#447]
**Tool and Version**
EarlyBoundGenerator V2 2.2023.5.13

**Describe the bug**
If you choose the option Delete Files from Output folders = True but then also choose the option "Generate Messages" = false

The process throws the following exception:

 An error when calling ProcessModelInvoker.Invoke.  Result: 2
Log File:
System.ArgumentNullException: Value cannot be null.
Parameter name: path2
   at System.IO.Path.Combine(String path1, String path2)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.DeleteExistingFiles()
   at DLaB.ModelBuilderExtensions.CodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)

**To Reproduce**
Set Delete Files from Output folders = True
Set Generate Messages = false

**Expected behavior**
Should be allowed to delete files if one is not generating messages

**Additional context**
The error can be bypassed by Generating the messages cs file or choosing not to delete files, but if not generating many early bound classes and option sets, this just adds unnecessary time to generate the messages cs file

**Comment by daryllabar** [comment]
Fix is in the latest version.
