### ISSUE TITLE
System.Exception: Error attempting to GenerateAttributeNameConsts!  Unable to find attribute fileid in Solution

### ISSUE THREAD

**Issue by tmykhaylovsky** [daryllabar/DLaB.Xrm.XrmToolBoxTools#450]
What tool/version is it that you're reporting a bug for? i.e.
EarlyBoundGenerator V 2.2023.5.13

**Describe the bug**
Added Solution to entity whitelist and it's unable to generate the class

**To Reproduce**
1. Open Early Bound Generator V2 plugin
2. Load the XML setting file
3. Go to setting section 2: Entities
4. Edit Entities Whitelist
5. Add Solution to the existing list of whitelisted entities
6. Click Generate
7. Observe error: System.Exception: Error attempting to GenerateAttributeNameConsts!  Unable to find attribute fileid in Solution

**Expected behavior**
Solution class would be generated in EarlyBoundGenerator/Entities folder

**Screenshots**
N/A, but can add by request

**Additional context**
I have these entities whitelisted: Attribute, Entity, Entity Relationship, a custom entity, and System Form as other whitelisted entities

Thank you for reviewing!

**Comment by bwmodular** [comment]
If it helps to know this, I'm getting the same issue but for the Post entity.
_Error attempting to GenerateAttributeNameConsts!  Unable to find attribute postregardingid in Post_
This is my first attempt at using the v2 generator - using a settings file which was created using 'v1' EBG. Same settings file still works fine with EBG 1.

**Comment by daryllabar** [comment]
I'm unable to replicate this, can one of you attach a zip of the metadata and settings files here, as outlined in the wiki https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/EBG-%E2%80%90-Submitting-Metadata-For-Debugging

**Comment by bwmodular** [comment]
Hi Daryl,
I removed everything except the Post entity from the whitelist and kicked it off.
It failed again.
I've included a zip wile with the serialized metadata, the builder.json and the log file.

[EBGFailure29Nov23.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/13498589/EBGFailure29Nov23.zip)

Hope that helps.

Given that the settings file is migrated from 'v1' to v2 of the EBG I will try starting from scratch with a new settings file to see if that works - I'll let you know.

Best wishes,
Ben

**Comment by bwmodular** [comment]
Hi Daryl,
I connected to a different environment with the same metadata as the one I was using earlier, opened EBG V2 and left all the settings as default apart from the Entity Whitelist, where I removed all of the default entities and added the Post entity.
Hit Generate and got the same error: Unable to find attribute postregardingid in Post

So, I guess this rules out any issues with starting out with a V1 settings file and switching to V2.

EBG v2 is running against a D365 online instance, 2023 Wave 2 applied, v 9.2.23105.00230

Let me know if I can provide any more information.

**Comment by daryllabar** [comment]
Your file is missing your Settings xml file.   Can you add that as well?

**Comment by daryllabar** [comment]
Can you try downloading, unblocking, and then extracting this file in to your XTB plugins folder and giving it a try?

[DLaB.EarlyBoundGeneratorV2.zip](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/files/13502368/DLaB.EarlyBoundGeneratorV2.zip)

**Comment by bwmodular** [comment]
Hi Daryl,
it took me a while to get the new version you sent over working because Norton had helpfully quarantined half of the dll's in the zip file!
Once I sorted that the immediate problem is fixed. 

I did get the following error though:

Method	: BuildResponseField
Date	: 12:28:25
Time	: 30/11/2023
Error	: Type Microsoft.Xrm.Sdk.PreferredSolutionDetails is not available
Stack Trace	: at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildResponseField(SdkMessageResponse response, SdkMessageResponseField field, ServiceProvider serviceProvider)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildMessageResponse(SdkMessagePair messagePair, SdkMessageResponse sdkMessageResponse, ServiceProvider serviceProvider)

 0: Warning     - Skipping PreferredSolutionUsedBy.Message Pair from being generated. - Supporting Types Missing
 0: Information  - Wrote 734 Message(s). Skipped 1015 Message(s) - 00:00:00.7714481

and I now have a solution with several thousand compilation errors, mostly compaining about mssing types in the generated classes:
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/1889586/8dbc4996-f7d0-4805-883c-44fc13e38c8f)

I did look your suggested wiki page: https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/Version-2.2023.4.3-Upgrade-To-PAC-ModelBuilder
but that doesn't exist yet :-)

I'll try a few things out and see if I can get things working, but any tips on switching to v2 would be very useful if you have them.
Thanks so much,
Ben

**Comment by daryllabar** [comment]
@bwmodular you're on the latest version of the XTB, correct?

**Comment by bwmodular** [comment]
Yes, latest version of XTB....

**Comment by bwmodular** [comment]
Hi Daryl, 
back looking at v2 today after our v1 detour yesterday. 😉
Couple of things to mention.

**1.)** The new version you posted above resolves the original '_Error attempting to GenerateAttributeNameConsts!_' issue. The Generate process now fails with this error for me:
_[ 0: Information ] - Wrote 96 Entities - 00:00:01.8216569
[ 0: Information ] - Processing 1749 Messages
[ 0: Error       ] - Source	: Microsoft.PowerPlatform.Dataverse.ModelBuilderLib
Method	: BuildResponseField
Date	: 09:28:02
Time	: 01/12/2023
Error	: Type Microsoft.Xrm.Sdk.PreferredSolutionDetails is not available
Stack Trace	: at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildResponseField(SdkMessageResponse response, SdkMessageResponseField field, ServiceProvider serviceProvider)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildMessageResponse(SdkMessagePair messagePair, SdkMessageResponse sdkMessageResponse, ServiceProvider serviceProvider)_

The error still occurs if I revert to a default settings file, rather than an upgraded v1 file.

**2.)** At some point when running the tool yesterday, it pointed me at this page.
https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/Version-2.2023.4.3-Upgrade-To-PAC-ModelBuilder
However, that page doesn't exist - it should probably point here:
https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/EBG-%E2%80%90-Version-2.2023.4.3-Upgrade-To-PAC-ModelBuilder
which I found just now and will read through to see if there are any hints in there that I've missed.
I'm not sue when it actually pointed me at that page as it's not doing so today, but it was defintely there in the logs at some point.

Let me know if I can provide any more info on the current issue.

**Comment by daryllabar** [comment]
> Hi Daryl, back looking at v2 today after our v1 detour yesterday. 😉 Couple of things to mention.
> 
> **1.)** The new version you posted above resolves the original '_Error attempting to GenerateAttributeNameConsts!_' issue. The Generate process now fails with this error for me: _[ 0: Information ] - Wrote 96 Entities - 00:00:01.8216569 [ 0: Information ] - Processing 1749 Messages [ 0: Error ] - Source : Microsoft.PowerPlatform.Dataverse.ModelBuilderLib Method : BuildResponseField Date : 09:28:02 Time : 01/12/2023 Error : Type Microsoft.Xrm.Sdk.PreferredSolutionDetails is not available Stack Trace : at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildResponseField(SdkMessageResponse response, SdkMessageResponseField field, ServiceProvider serviceProvider) at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildMessageResponse(SdkMessagePair messagePair, SdkMessageResponse sdkMessageResponse, ServiceProvider serviceProvider)_
> 
> The error still occurs if I revert to a default settings file, rather than an upgraded v1 file.
> 
> **2.)** At some point when running the tool yesterday, it pointed me at this page. https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/Version-2.2023.4.3-Upgrade-To-PAC-ModelBuilder However, that page doesn't exist - it should probably point here: https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/wiki/EBG-%E2%80%90-Version-2.2023.4.3-Upgrade-To-PAC-ModelBuilder which I found just now and will read through to see if there are any hints in there that I've missed. I'm not sue when it actually pointed me at that page as it's not doing so today, but it was defintely there in the logs at some point.
> 
> Let me know if I can provide any more info on the current issue.

#456 Fixed the first issue you had and #457 will fix the URL issue. 

As far as your current issue, please wait until the next version of the XTB is deployed, there is a fix in the assembly loading that will allow me to actually push a version of the EBGV2 without having to ILMerge, which I think is causing the issue that you're seeing.

**Comment by bwmodular** [comment]
Wonderful, thanks! I’ll test with the next version of XTB…

**Comment by daryllabar** [comment]
> Wonderful, thanks! I’ll test with the next version of XTB…

And you'll need to wait for me to actually publish the next version of the EBGV2.

**Comment by daryllabar** [comment]
Fix is in the latest version.
