### ISSUE TITLE
Audible Completion Notification setting don't work

### ISSUE THREAD

**Issue by eshmaya** [daryllabar/DLaB.Xrm.XrmToolBoxTools#452]
What tool/version is it that you're reporting a bug for? i.e.
Early Bound Generator V2 - V2.2023.5.13

**Describe the bug**
After generating data model I get an error:
Audio Device Error (Working on VM without Sound Card) even if the Audible Completion Notification is set to false in the Global setting section.

**To Reproduce**
1. Open the tool and connect to an organization.
2. Set the value of Audible Completion Notification to false.
3. Click Generate

System.Speech.Internal.Synthesis.AudioException: Audio device error encountered. - Error Code: 0x2
   at System.Speech.Internal.Synthesis.VoiceSynthesis.Speak(Prompt prompt)
   at DLaB.EarlyBoundGeneratorV2.Logic.Speak(String words)
   at DLaB.EarlyBoundGeneratorV2.Logic.Create(IOrganizationService service)
   at DLaB.EarlyBoundGeneratorV2.EarlyBoundGeneratorPlugin.<CreateCode>b__49_0(BackgroundWorker w, DoWorkEventArgs e)

System.Speech.Internal.Synthesis.AudioException: Audio device error encountered. - Error Code: 0x2
   at System.Speech.Internal.Synthesis.VoiceSynthesis.Speak(Prompt prompt)
   at DLaB.EarlyBoundGeneratorV2.Logic.Speak(String words)
   at DLaB.EarlyBoundGeneratorV2.Logic.Create(IOrganizationService service)
   at DLaB.EarlyBoundGeneratorV2.EarlyBoundGeneratorPlugin.<CreateCode>b__49_0(BackgroundWorker w, DoWorkEventArgs e)

**Expected behavior**
The software should not try to notify using audible if the settings Audible Completion Notification set to false

**Comment by daryllabar** [comment]
Fix is in the latest version.
