### ISSUE TITLE
Not able to generate earlybound for Solution entity using Earlybound generator V2

### ISSUE THREAD

**Issue by JEET391** [daryllabar/DLaB.Xrm.XrmToolBoxTools#458]
**Tool and Version**
What tool/version is it that you're reporting a bug for? i.e.
EarlyBoundGenerator V 1.2020.4.24

**Describe the bug**
Log File:
System.Exception: Error attempting to GenerateAttributeNameConsts!  Unable to find attribute fileid in Solution
   at DLaB.ModelBuilderExtensions.Entity.AttributeConstGenerator.CustomizeCodeDom(CodeCompileUnit codeUnit, IServiceProvider services)
   at DLaB.ModelBuilderExtensions.CustomizeCodeDomService.ProcessEntity(CodeCompileUnit codeUnit, IServiceProvider services)
   at DLaB.ModelBuilderExtensions.CustomizeCodeDomService.CustomizeCodeDom(CodeCompileUnit codeUnit, IServiceProvider services)
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.WriteFile(String outputFile, String language, CodeNamespace codenamespace, IServiceProvider serviceProvider, Boolean writeProxyAttrib, Boolean isFileSplit)
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider serviceProvider)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
Generation Complete!
---
- Deployment: Online
- DB Version: 9.2.23104.248
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.10.67
- Tool Version: 2.2023.5.13

**Comment by daryllabar** [comment]
Duplicate of #450 it does have a zip file in that story that has a version you can try to use.  I had to ILMerge a whole bunch of stuff due to a bug in the XTB, so it may not work, but once a new version of the XTB is released, and can release the non-ILMerged version.
