### ISSUE TITLE
The process cannot access the file

### ISSUE THREAD

**Issue by RodneyBarabasz** [daryllabar/DLaB.Xrm.XrmToolBoxTools#498]
**Tool and Version**
EarlyBoundGenerator V2.2024.5.11

**Describe the bug**
Running the Early Bound Generation for a Power Platform Dataverse environment results in "The process cannot access the file" and fails on the creation of the first Entity file. It creates the first entity file, but nothing further.

**To Reproduce**
Generate classes in the tool in XrmToolKit. 

**Expected behavior**
All Entity and OptionSet files are generated. This worked with the same settings file in a previous version before upgrading to the latest version of the tool

**Log**
Loading settings from C:\_TerandiCode\BCMS\src\StrataData.BCMS.Plugins\EarlyBoundGeneratorV2Settings.xml
CRM Authentication Type Detected: OnlineFederation
Tracking Generation Event.
Updating Builder Settings
Generating Early Bound Files
Generating ProcessModelInvoker Arguments:
--splitfiles
--outdirectory C:\_TerandiCode\BCMS\src\StrataData.BCMS.Plugins
--settingsTemplateFile C:\_TerandiCode\BCMS\src\StrataData.BCMS.Plugins\builderSettings.json
Finished Generating ProcessModelInvoker Arguments.
Command line for Cloud generation:
PAC modelbuilder build --outdirectory C:\_TerandiCode\BCMS\src\StrataData.BCMS.Plugins --settingsTemplateFile C:\_TerandiCode\BCMS\src\StrataData.BCMS.Plugins\builderSettings.json
[ 0: Information ] - Dataverse Model Builder :  [Version 2.0.0.11]
[ 0: Information ] - © 2022 Microsoft Corporation. All rights reserved
[ 0: Information ] - 
[ 0: Information ] - Begin reading metadata from MetadataProviderService
[ 0: Information ] - Looking for custom extension named DLaB.ModelBuilderExtensions.CodeWriterFilterService,DLaB.ModelBuilderExtensions for 
[ 0: Information ] - Looking for custom extension named DLaB.ModelBuilderExtensions.CodeWriterMessageFilterService,DLaB.ModelBuilderExtensions for 
[ 0: Information ] - Looking for custom extension named DLaB.ModelBuilderExtensions.MetadataProviderService,DLaB.ModelBuilderExtensions for 
[ 0: Information ] - Looking for custom extension named DLaB.ModelBuilderExtensions.MetadataQueryProviderService,DLaB.ModelBuilderExtensions for 
[ 0: Information ] - Looking for custom extension named DLaB.ModelBuilderExtensions.CodeGenerationService,DLaB.ModelBuilderExtensions for 
[ 0: Information ] - Looking for custom extension named DLaB.ModelBuilderExtensions.NamingService,DLaB.ModelBuilderExtensions for 
[ 0: Information ] - Looking for custom extension named DLaB.ModelBuilderExtensions.CustomizeCodeDomService,DLaB.ModelBuilderExtensions for 
[ 0: Information ] - Begin Reading Metadata from Server
[ 0: Information ] - Read 9 Entities - 00:00:00.801
[ 0: Information ] - Read 154 Global OptionSets - 00:00:00.131
[ 0: Information ] - Read 1082 SDK Messages - 00:00:02.078
[ 0: Information ] - Completed Reading Metadata from Server - 00:00:03.076
[ 0: Information ] - Completed reading metadata from MetadataProviderService - 00:00:03.079
[ 0: Information ] - Begin Writing Code Files
[ 0: Information ] - Processing 9 Entities
[ 0: Warning     ] - Skipping OptionSet socialprofile_community. OptionSet is a global optionset, skipping entity level add.
[ 0: Warning     ] - Skipping OptionSet activitypointer_deliveryprioritycode. OptionSet is a global optionset, skipping entity level add.
[ 0: Warning     ] - Skipping OptionSet powerpagelanguages. OptionSet is a global optionset, skipping entity level add.
[ 0: Warning     ] - Skipping OptionSet activitypointer_deliveryprioritycode. OptionSet is a global optionset, skipping entity level add.
[ 0: Warning     ] - Skipping OptionSet sd_accountingtype. OptionSet is a global optionset, skipping entity level add.
[ 0: Warning     ] - Skipping OptionSet sd_company. OptionSet is a global optionset, skipping entity level add.
[ 0: Warning     ] - Skipping OptionSet sd_fund. OptionSet is a global optionset, skipping entity level add.
[ 0: Warning     ] - Skipping OptionSet sd_incomebalance. OptionSet is a global optionset, skipping entity level add.
[ 0: Warning     ] - Skipping OptionSet sd_incomeorexpense. OptionSet is a global optionset, skipping entity level add.
[ 0: Information ] - Wrote 9 Entities - 00:00:00.3673488
[ 0: Information ] - Processing 1082 Messages
[ 0: Error       ] - Source	: Microsoft.PowerPlatform.Dataverse.ModelBuilderLib
Method	: BuildRequestField
Date	: 3:08:39 PM
Time	: 17/05/2024
Error	: Type Microsoft.Xrm.Sdk.BulkRemoveActiveCustomizationsParameters is not available
Stack Trace	: at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildRequestField(SdkMessageRequest request, SdkMessageRequestField field, ServiceProvider serviceProvider)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildMessageRequest(SdkMessagePair messagePair, SdkMessageRequest sdkMessageRequest, ServiceProvider serviceProvider)
======================================================================================================================

[ 0: Warning     ] - Skipping BulkRemoveActiveCustomizationsAsync.Message Pair from being generated. - Supporting Types Missing
[ 0: Error       ] - Source	: Microsoft.PowerPlatform.Dataverse.ModelBuilderLib
Method	: BuildRequestField
Date	: 3:08:39 PM
Time	: 17/05/2024
Error	: Type Microsoft.Xrm.Sdk.AddComponentToSolutionParametersCollection is not available
Stack Trace	: at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildRequestField(SdkMessageRequest request, SdkMessageRequestField field, ServiceProvider serviceProvider)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildMessageRequest(SdkMessagePair messagePair, SdkMessageRequest sdkMessageRequest, ServiceProvider serviceProvider)
======================================================================================================================

[ 0: Warning     ] - Skipping AddComponentsToSolutionAsync.Message Pair from being generated. - Supporting Types Missing
[ 0: Error       ] - Source	: Microsoft.PowerPlatform.Dataverse.ModelBuilderLib
Method	: BuildResponseField
Date	: 3:08:39 PM
Time	: 17/05/2024
Error	: Type Microsoft.Xrm.Sdk.PreferredSolutionDetails is not available
Stack Trace	: at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildResponseField(SdkMessageResponse response, SdkMessageResponseField field, ServiceProvider serviceProvider)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.CodeGenerationService.BuildMessageResponse(SdkMessagePair messagePair, SdkMessageResponse sdkMessageResponse, ServiceProvider serviceProvider)
======================================================================================================================

[ 0: Warning     ] - Skipping PreferredSolutionUsedBy.Message Pair from being generated. - Supporting Types Missing
[ 0: Information ] - Wrote 232 Message(s). Skipped 850 Message(s) - 00:00:00.3000592
[ 0: Information ] - Processing 154 Global OptionSets
[ 0: Warning     ] - Skipping OptionSet sla_slaenabledentities. OptionSet contains no Options and would generate an empty enum.
[ 0: Warning     ] - Skipping OptionSet selectedmobileofflineenabledentityrelationships. OptionSet contains no Options and would generate an empty enum.
[ 0: Warning     ] - Skipping OptionSet documenttemplate_associatedentitytypecode. OptionSet contains no Options and would generate an empty enum.
[ 0: Information ] - Wrote 105 Global OptionSets - 00:00:00.0475113
System.IO.IOException: The process cannot access the file 'C:\_TerandiCode\BCMS\src\StrataData.BCMS.Plugins\Entities\Account.cs' because it is being used by another process.
[ 0: Error       ] - Exiting program with exit code 2 due to exception : System.IO.IOException: The process cannot access the file 'C:\_TerandiCode\BCMS\src\StrataData.BCMS.Plugins\Entities\Account.cs' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.WriteAllLines(String path, IEnumerable`1 contents, Encoding encoding)
   at DLaB.ModelBuilderExtensions.CustomTextWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.WriteFile(String outputFile, String language, CodeNamespace codenamespace, IServiceProvider serviceProvider, Boolean writeProxyAttrib, Boolean isFileSplit)
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider serviceProvider)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ModelBuilder.WriteCode(IOrganizationMetadata organizationMetadata)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ModelBuilder.Run()
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ModelBuilder.Invoke(IOrganizationService serviceClient)
[ 0: Error       ] - ===== DETAIL ======
[ 0: Error       ] - Source	: mscorlib
Method	: WinIOError
Date	: 3:08:39 PM
Time	: 17/05/2024
Error	: The process cannot access the file 'C:\_TerandiCode\BCMS\src\StrataData.BCMS.Plugins\Entities\Account.cs' because it is being used by another process.
Stack Trace	: at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.WriteAllLines(String path, IEnumerable`1 contents, Encoding encoding)
   at DLaB.ModelBuilderExtensions.CustomTextWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.WriteFile(String outputFile, String language, CodeNamespace codenamespace, IServiceProvider serviceProvider, Boolean writeProxyAttrib, Boolean isFileSplit)
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider serviceProvider)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ModelBuilder.WriteCode(IOrganizationMetadata organizationMetadata)
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ModelBuilder.Run()
   at Microsoft.PowerPlatform.Dataverse.ModelBuilderLib.ModelBuilder.Invoke(IOrganizationService serviceClient)
======================================================================================================================

 An error when calling ProcessModelInvoker.Invoke.  Result: 2
Log File:
System.IO.IOException: The process cannot access the file 'C:\_TerandiCode\BCMS\src\StrataData.BCMS.Plugins\Entities\Account.cs' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding)
   at System.IO.File.WriteAllLines(String path, IEnumerable`1 contents, Encoding encoding)
   at DLaB.ModelBuilderExtensions.CustomTextWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.WriteFile(String outputFile, String language, CodeNamespace codenamespace, IServiceProvider serviceProvider, Boolean writeProxyAttrib, Boolean isFileSplit)
   at DLaB.ModelBuilderExtensions.PacModelBuilderCodeGenHack.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider serviceProvider)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
   at DLaB.ModelBuilderExtensions.CodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
Generation Complete!

**Comment by daryllabar** [comment]
Any chance you have the file open in another program?

**Comment by Marvinnnne** [comment]
I had the same issue. I uninstall and reinstall Early Bound Generator V2.
Now I can't reopen xrmtoolbox because of this error, I don't know if it's linked
![image](https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/assets/9744563/dd454ac4-53ab-4963-a6bc-011243a9be0e)

**Comment by daryllabar** [comment]
Found the the problem.  Fix coming within the hour.

**Comment by Marvinnnne** [comment]
With version 2.2024.5.16, it works. Thanks !

**Comment by daryllabar** [comment]
Please download 

> With version 2.2024.5.16, it works. Thanks !

Someone was refreshing quite a lot...
