### ISSUE TITLE
Error on entity generation

### ISSUE THREAD

**Issue by reager** [daryllabar/DLaB.Xrm.XrmToolBoxTools#5]
I had your excellent plugin working, but after (I guess) configuration in CRM I only receives this error message every time I try to run the entity generator

    Exception attempting to GetDictionaryList for config key: duplicaterule,BaseEntityTypeCode,MatchingEntityTypeCode|invoicedetail,InvoiceStateCode|leadaddress,AddressTypeCode,ShippingMethodCode|organization,CurrencyFormatCode,DateFormatCode,TimeFormatCode,WeekStartDayCode|quote,StatusCode|quotedetail,QuoteStateCode|salesorderdetail,SalesOrderStateCode|DuplicateRule,BaseEntityTypeCode,MatchingEntityTypeCode|InvoiceDetail,InvoiceStateCode|LeadAddress,AddressTypeCode,ShippingMethodCode|Organization,CurrencyFormatCode,DateFormatCode,TimeFormatCode,WeekStartDayCode|Quote,StatusCode|QuoteDetail,QuoteStateCode|SalesOrderDetail,SalesOrderStateCode
    System.ArgumentException: An item with the same key has already been added.
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at DLaB.CrmSvcUtilExtensions.ConfigHelper.GetDictionaryList(String value, Boolean lowerCaseValues)
    System.ArgumentException: An item with the same key has already been added.
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at DLaB.CrmSvcUtilExtensions.ConfigHelper.GetDictionaryList(String value, Boolean lowerCaseValues)
       at DLaB.CrmSvcUtilExtensions.Entity.EnumPropertyGenerator.InitializeMappings()
       at DLaB.CrmSvcUtilExtensions.Entity.EnumPropertyGenerator.CustomizeCodeDom(CodeCompileUnit codeUnit, IServiceProvider services)
       at DLaB.CrmSvcUtilExtensions.Entity.CustomizeCodeDomService.CustomizeCodeDom(CodeCompileUnit codeUnit, IServiceProvider services)
       at Microsoft.Crm.Services.Utility.CodeGenerationService.WriteFile(String outputFile, String language, CodeNamespace codenamespace, ServiceProvider serviceProvider)
       at Microsoft.Crm.Services.Utility.CodeGenerationService.Microsoft.Crm.Services.Utility.ICodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String outputNamespace, IServiceProvider services)
       at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.WriteInternal(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)
       at DLaB.CrmSvcUtilExtensions.BaseCustomCodeGenerationService.Write(IOrganizationMetadata organizationMetadata, String language, String outputFile, String targetNamespace, IServiceProvider services)

**Comment by daryllabar** [comment]
Looks like it is related to duplicate rules.  I usually don't use them.  I'll see if I can figure out what the issue is and maybe even create some duplicate rules myself

**Comment by daryllabar** [comment]
Looks like your UnmappedProperties in the DLaB.EarlyBoundGenerator.Settings.xml has duplicate values in it.  Try manually editing the file, and replacing the UnmappedProperties node with the following:
   
     <UnmappedProperties>DuplicateRule,BaseEntityTypeCode,MatchingEntityTypeCode|InvoiceDetail,InvoiceStateCode|LeadAddress,AddressTypeCode,ShippingMethodCode|Organization,CurrencyFormatCode,DateFormatCode,TimeFormatCode,WeekStartDayCode|Quote,StatusCode|QuoteDetail,QuoteStateCode|SalesOrderDetail,SalesOrderStateCode|</UnmappedProperties>

Did recently update the plugin, or edit a value in the Unmapped Properties in the UI?

**Comment by TarogStar** [comment]
I have seen duplicate properties show up sometimes with this error, I have just manually edited the duplicates out of the xml file.  I was using the GUI to update everything and it duplicated multiple times as I was using it.  If it happens again I'll look for more specific info to figure out what might be causing the issue.

**Comment by daryllabar** [comment]
Thanks @TarogStar  for commenting.  I've removed the saving of the settings from running the background process.  Maybe it is a race condition that may be causing the issue.  If you're able to find a recreation, let me know.
