### ISSUE TITLE
Error generating option sets using default settings - null argument

### ISSUE THREAD

**Issue by digiface** [daryllabar/DLaB.Xrm.XrmToolBoxTools#64]
Error:

System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
   at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, String replacement)
   at DLaB.CrmSvcUtilExtensions.NamingService.GetValidCSharpName(String name)
   at DLaB.CrmSvcUtilExtensions.NamingService.GetDuplicateNameValues(OptionSetMetadataBase metadata, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.NamingService.AppendValueForDuplicateOptionSetValueNames(OptionSetMetadataBase optionSetMetadata, String name, Nullable`1 value, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.NamingService.GetNameForOption(OptionSetMetadataBase optionSetMetadata, OptionMetadata optionMetadata, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.NamingService.GetNameForOption(OptionSetMetadataBase optionSetMetadata, OptionMetadata optionMetadata, IServiceProvider services)
   at DLaB.CrmSvcUtilExtensions.OptionSet.CodeWriterFilterService.GenerateOptionSet(OptionSetMetadataBase optionSetMetadata, IServiceProvider services)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildAttributeOptionSet(EntityMetadata entity, AttributeMetadata attribute, CodeTypeMember attributeMember, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildEntity(EntityMetadata entity, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildEntities(EntityMetadata[] entityMetadata, ServiceProvider serviceProvider)
   at Microsoft.Crm.Services.Utility.CodeGenerationService.BuildCodeDom(IOrganizationMetadata organizationMetadata, String outputNamespace, ServiceProvider serviceProvider)

**Comment by daryllabar** [comment]
Can you try the zip file at the bottom of https://github.com/daryllabar/DLaB.Xrm.XrmToolBoxTools/issues/61 to see if it resolves your issue?

**Comment by digiface** [comment]
Yes that works, thanks for that :)
